### PR TITLE
Use 'click' event for checkbox and radio (fix #4620)

### LINKED ISSUE #4620: Checkbox :checked is not fully reactive when checkbox is in focus
Example: https://jsfiddle.net/vfmxxzeb/3/

What the example does:
1. Resets `values` to an array of values every one second
2. Each line has two checkboxes, both of which are bound to the same value

Steps to reproduce:
1. *Click* on the enabled checkbox on any line

Expected behaviour:
1. After one second, the value should be reset. Both checkboxes should reflect the same value

Actual behaviour (tested on Chrome):
1. The disabled checkbox correctly reflects the value, but the enabled checkbox does not reflect the value. The enabled checkbox will reflect the correct value only after blurring from the checkbox

### PR DESCRIPTION
**Pull request by defcc**
fix #4620 

1. use *click* event instead of *change* event.
2. add test case for #4521

### CODE REVIEW

**Comment by sirlancelot** [comment]
Will this event still trigger if someone isn't clicking it? For instance, through keyboard tabbing & spacebar?

**Comment by defcc** [comment]
Keyboard's spacebar will change the checkbox's checked status and trigger click event on Mac Chrome. If the browser supports the spacebar, it should also trigger the click event. 

https://www.w3.org/TR/WCAG20-TECHS/SCR35

**Comment by yyx990803** [comment]
Hmm, the CI failed after merging (but it was passing for the PR itself...) Need to investigate a bit more.

**Comment by defcc** [comment]
I'll take a look.

**Comment by defcc** [comment]
Something wrong with the checkbox test case. The checkbox and radio need the same test case, so I made a mistake when doing  it.  I'll check why it works in the PR.

**Comment by defcc** [comment]
I'll also update the contribution guide later.

**Pull request merged**
