### PR TITLE
add pagination

### PR DESCRIPTION
**Pull request by wizardpisces**
add basic pagination

### CODE REVIEW

**Comment by amirrustam** [comment]
@wizardpisces thanks for the contribution. Please make sure you code conforms to the outlined project [code style rules](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md#code-style) before merging. The style rules specify **2 space indentations**.

**Comment by wizardpisces** [comment]
thank you for you reminding

**Comment by yyx990803** [comment]
Thanks for the PR, a few things:

1. Please use ESLint to lint your JavaScript code - the current code still doesn't meet the code style requirements

2. There are many places (template/css/js) where you have inconsistent use of spaces, sometimes there are spaces before braces/parens, sometimes there aren't.

3. Please do not use Chinese in the examples.

**Comment by azamat-sharapov** [comment]
Still Chinese in index.html :)

**Comment by nervgh** [comment]
I think the pagination must have [more options](https://github.com/nervgh/angular-pagination/blob/master/src/pagination.js#L9) :smiley:

**Comment by wizardpisces** [comment]
thank you for your tip, you may fork  as you like

**Comment by yyx990803** [comment]
Thanks for the PR, but unfortunately there are still numerous unfixed style issues and I think pagination is something that is better explained with an actual server data sources.

**Pull request closed without merging**
