### PR TITLE
mini change: removed unnecessary spaces

### PR DESCRIPTION
**Pull request by Jinjiang**
before comment of `resolveDynamicComponent` in `src/directives/repeat.js`

### CODE REVIEW

**Comment by azamat-sharapov** [comment]
PR of the month

**Comment by yyx990803** [comment]
LOL congrats on first PR :)

**Comment by buaabyl** [comment]
this PR it is real! ......

**Comment by wqj97** [comment]
hahahaha
from zhihu

**Comment by lzskyline** [comment]
zhihu +1

**Comment by zchazc** [comment]
A special and careful commit.

melon-eating netizen from Zhihu:)

**Comment by qrqhuang** [comment]
came from zhihu too..

**Comment by uicheung** [comment]
i have find another spaces 
???

**Comment by LRY89757** [comment]
zhihu, too....

**Comment by zkj881225** [comment]
zhihu,too,but can't understand this joy?anyone tell me in chinese?

**Comment by GLFei** [comment]
Me too.

**Comment by xiaolonggee** [comment]
> zhihu,too,but can't understand this joy?anyone tell me in chinese?
因为这个PR根本太没必要了吧

**Comment by qingdkj** [comment]
from Zhihu, too
lol

**Comment by Aquarius-JS** [comment]
from vue conf24
hahaha

**Comment by hanshinn** [comment]
From ZhiHu, too. Hahahaha... It's so funny.

**Comment by fadeds** [comment]
Come and have a look

**Pull request merged**
