### PR TITLE
refactor: get the vendor style name in the style directive

### PR DESCRIPTION
**Pull request by gebilaoxiong**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by gebilaoxiong** [comment]
Do not have to get the `div style` every time

**Comment by posva** [comment]
I think the names were better before. I'm not sure if directly caching the `style` object has any impact (ie: does the browser replace the reference of the element at some time?)
I thought Opera had `webkit` prefixes

**Comment by gebilaoxiong** [comment]
@posva Thanks for your advice.

I removed Opera from `vendorNames`

good night. 🌝

**Comment by posva** [comment]
@gebilaoxiong haha, I wasn't even sure about that!
I checked and it looks like the `o` prefix was necessary in older versions of opera

**Comment by gebilaoxiong** [comment]
@posva 

e.... what should I do now .... 😭

**Comment by gebilaoxiong** [comment]
@posva  @yyx990803 

thanks

**Pull request merged**
