### PR TITLE
Reverse filters support for v1.0

### PR DESCRIPTION
**Pull request by karevn**
Continuation of this work: https://github.com/vuejs/vue/pull/1441

### CODE REVIEW

**Comment by yyx990803** [comment]
:+1: thanks!

**Comment by yyx990803** [comment]
Unfortunately, had to revert this because this actually neglects a use case where the user attempts to use `v-model` on a `v-for` alias with a read-only filter, e.g. `orderBy`. This is in fact pretty common and is what the original warning is trying to prevent.

With this PR, such use case no longer receives a warning and actually writes the value back to the original array at the wrong index.

**Comment by karevn** [comment]
Ok. Any ideas for enhancements?
16 нояб. 2015 г. 21:50 пользователь "Evan You" <notifications@github.com>
написал:

**Comment by yyx990803** [comment]
I tried working on top of your PR but haven't had a clean solution yet. Will take a deeper look later this week.

**Comment by karevn** [comment]
I think we should figure out use cases first. :)
16 нояб. 2015 г. 22:05 пользователь "Evan You" <notifications@github.com>
написал:

**Pull request merged**
