### PR TITLE
fix: v-model avoid triggering extra input event in firefox

### PR DESCRIPTION
**Pull request by xiaodemen**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by posva** [comment]
Can you provide a proper bug report please?

**Comment by xiaodemen** [comment]
demo: https://codepen.io/xiaodemen/pen/pogYyOj

**Comment by Justineo** [comment]
@xiaodemen You need to elaborate on how this PR fixes the problem because it’s not very easy to understand.

**Comment by xiaodemen** [comment]
Order of composition events is: 

Chrome: `compositionstart` -> ...  -> `compositionupdate` -> `input` -> `compositionend`(vue fires a sync` input`) 

Firefox: `compositionstart` -> ... -> `compositionupdate` -> `compositionend`(vue fires a sync` input`) -> `input`

So `v-model` set value twice  in Firefox, which is redundant. 

This PR fixes bug via only firing a `input` in  `compositionend` which immediately follows `compositionupdate` -> `input`.

**Comment by Justineo** [comment]
Native behavior:

```
// Chrome
start ... update ... input ... end
          ~~~~~~~~~~~~~~~~~~~~~~~~ last composition

// Firefox
start ... update ... end ... input
          ~~~~~~~~~~~~~~~~~~~~~~~~ last composition
```

Because we want to ignore composition events in `v-model`, current behavior always dispatches an `input` event after `compositionend`:

```
// Chrome
[start ... update ... input ... end] ... input (by Vue)
                      ~~~~~ ignored      ~~~~~ triggered

// Firefox
[start ... update ... end] ... input (by Vue) ... input
                               ~~~~~ triggered    ~~~~~ triggered
```

So in Firefox we will get two consecutive `input` events triggered with same value.

This fix watches the `compositionupdate` & `input` event sequence during composition, and only dispatch an input event when `compositionend` is immediately following a `compositionupdate` event, not an `input` event. So now it becomes:

```
// Chrome
[start ... update ... input ... end] ... input (by Vue)
                      ~~~~~ ignored      ~~~~~ triggered

// Firefox
[start ... update ... end] ... (removed) ... input
                                             ~~~~~ triggered
```

**Comment by RonaldJerez** [comment]
Is this change been considered? This issue is causing [vue-input-facade](https://github.com/RonaldJerez/vue-input-facade) to emit multiple inputs from firefox

**Pull request closed without merging**
