### PR TITLE
docs: use yarn instead of npm in scripts section

### PR DESCRIPTION
**Pull request by Justineo**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:

Documentation update.

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by kamalhm** [comment]
do vuejs recommends yarn as the package manager? I see the original page and it's kinda confusing, one part npm and one part yarn

**Comment by posva** [comment]
this is not about benefits when developing with Vue, it's about what is the setup to contribute to Vue. Using `npm` could lead to different packages version that would make tests fail when they shouldn't

**Comment by sirlancelot** [comment]
Is that still a problem though? I know `npm` before v3 had a hierarchical `node_modules` folder which led to duplicated versions of dependencies. I've been using a modern version of `npm` (v6.10.3) without any issues. Yarn is redundant IMO.

**Comment by Justineo** [comment]
As I know there are still subtle differences even between latest versions of npm and Yarn. Using Yarn while contributing to Vue is more reliable.

**Comment by posva** [comment]
Yes, it's a problem and it will always been because of tye lock files being different for yarn and npm

**Comment by Justineo** [comment]
Vue is now using pnpm instead.

**Pull request closed without merging**
