### PR TITLE
fix(keep-alive): cache what is really needed not the whole VNode…

### PR DESCRIPTION
**Pull request by zrh122**
cache what is really needed not the whole `VNode` data. it also fixes  [#9842](https://github.com/vuejs/vue/issues/9842)
Fixes [#2549](https://github.com/vuejs/vue-router/issues/2549)
Fixes [#9972](https://github.com/vuejs/vue/issues/9972)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by kadet1090** [comment]
Any update on when we can expect this PR to be merged?

**Comment by pcm0nk** [comment]
Can we have an update when this going to be merged? shouldnt this be `high priority` as it makes the app not usable after some time working and navigating. Also keep-alive has impact on page load. If this gets merged or at least a workaround is provided ( not removing keep-alive) would be nice.

**Comment by dyu** [comment]
I just noticed this bug too.  The kept-alive node is not being destroyed.  This is such a critical bug for a core component that's use by many

**Comment by chencmgithub** [comment]
> Any update on when we can expect this PR to be merged?

which version had  fixed  the bug ??

**Comment by RichieChoo** [comment]
Any news?

**Comment by posva** [comment]
@zrh122 Thanks a lot for this! I reopened a new one with a refactor to avoid creating a new function on every render: https://github.com/vuejs/vue/pull/12015

**Pull request closed without merging**
