### PR TITLE
feat(events): Allow emmitter wait async subscriber

### PR DESCRIPTION
**Pull request by Abuntxa**
Implementation suggestion for [#11048 feature request](https://github.com/vuejs/vue/issues/11048)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [X] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [X] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by Justineo** [comment]
Thanks for your contribution! But currently we have no plans to add new APIs to 2.x. You can use this feature as a userland plugin for now.

**Comment by Abuntxa** [comment]
Hi @Justineo,
The internal helper methods of vue aren't exposed externally (or I couldn't see them), which would obly to copy a big amount of code from vue.

My new emmit implementation makes use of the following dependant helper functions:

``` typescript
import {
  tip,
  toArray,
  hyphenate,
  formatComponentName,
  invokeWithErrorHandling
} from '../util/index'
import { isPromise } from 'shared/util'
```
The implementation of "invokeWithErrorHandling" is particularly tricky as it carries a lot of other dependencies for the error handling.

**Comment by Abuntxa** [comment]
This is not a bug request. 

It's a new feature request that doesn't have to be implented in the same way I did. 

I totally understand the reason for closing this pull request, but I don't see any reason for closing the feature request.

**Comment by Justineo** [comment]
See https://github.com/vuejs/vue-next/issues/635. It's already included in current implementation of Vue 3 (\wo a formal RFC yet) so maybe we'll consider to back port it to Vue 2 later.

**Comment by Abuntxa** [comment]
Thanks for the explanation. Everything makes sense now.

**Comment by yyx990803** [comment]
FYI this feature is removed in Vue 3.

**Pull request closed without merging**
