### PR TITLE
fix(events): rule of calling binded event handler (close #11014)

### LINKED ISSUE #11014: Sometimes bubbling stops working on Safari
### Version
2.6.11

### Reproduction link
[https://codesandbox.io/s/vue-safari-error-tg4mm](https://codesandbox.io/s/vue-safari-error-tg4mm)

### Steps to reproduce
The bug reproduction is quite specific, so please be patient

- open "App.vue" in safari (my version is 13.0.4 (15608.4.9.1.3))
- open the console so that you can watch the logs (the values ​​of "e.TimeStamp" and "attachedTimestamp" from https://github.com/vuejs/vue/blob/dev/dist/vue.esm.js#L7549 are logged)
- make sure that the variable "WITH_GENERATE_NEW_VUE" is false
- wait a while. at least about a minute
- click the "Press me" button several times to make sure that everything works. most likely, in the console there will be "e.timeStamp, attachTimestamp 0 0"

Now the difficult and not completely clear part
- change the value of the variable "WITH_GENERATE_NEW_VUE" to true
- without reloading the browser page, click on the button
- now, most likely, the log will change to something similar to "e.timeStamp, attachedTimestamp 0 51478"
- this is Safari and "e.timeStamp" (the first number in the logs) is zero, but after some time or a few clicks, it will begin to grow and now until it becomes more than the value of "attachedTimestamp", the click will not work

### What is expected?
click and method on it works

### What is actually happening?
in the above case, this check is not performed
https://github.com/vuejs/vue/blob/dev/dist/vue.esm.js#L7549

---
This is a specific situation - something like emulating an application in which there is a lot of legacy. different sections can be written on different technologies and sometimes this bug is caught when switching between sections. Unfortunately, I can’t even suggest how this bug is related to the instantiation of a new vue, maybe this is a coincidence

I think this can be fixed by adding "e.target.contains (e.currentTarget)" to the conditions specified in https://github.com/vuejs/vue/blob/dev/dist/vue.esm.js#L7549 but I don’t know if this will not affect performance

### PR DESCRIPTION
**Pull request by rx-837**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

The checkbox 'Refactor' is checked because of rules ordering was changed. The primary rule should have bigger priority than crutches.

### CODE REVIEW

**Comment by joaomlemos** [comment]
The fix looks good. Would be nice to have this merged 👍 !

**Comment by jo4santos** [comment]
:+1:

**Comment by toshi38** [comment]
Have tested this fix, can confirm that it fixes our issue.  Is there a chance of getting this merged so we don't need to have a patched version of Vue?

**Comment by s-tokutake** [comment]
is there any update on this? we suffer the same problem as this.

**Review by liu419249629 — COMMENTED** [review]
fix qt env

**Pull request closed without merging**
