### PR TITLE
Fixed "delcare" typo error

### PR DESCRIPTION
**Pull request by javisperez**
Fixed typo error when adding a data property without declaring it first.

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks for the PR - note that the only place that needs to be changed is in `src` - all the other files are auto-generated and should not be modified.

**Comment by javisperez** [comment]
Oh yes, sorry, my bad as i didn't know that packages folder was auto-generated i just did a "find - replace" to everything just in case i missed something. But dist wasn't in my plan :) do you want me to update the PR ?

**Comment by posva** [comment]
@javisperez Yes please 😄

**Comment by javisperez** [comment]
Done :D

**Pull request merged**
