### PR TITLE
fix: add URL in ssr sandbox global

### PR DESCRIPTION
**Pull request by clarkdo**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

**Other information:**

Related to https://github.com/nuxt/nuxt.js/issues/4914, when using `runInNewContext: true` and URL in server side, the URL is not injected on global object.

### CODE REVIEW

**Comment by pimlie** [comment]
Maybe we could add [`URLSearchParams`](https://nodejs.org/dist/latest-v12.x/docs/api/globals.html) as well?

Also please note that these classes are only available since Node v10, might be an issue.

**Comment by allanchua101** [comment]
Looks good to me 👍

**Comment by Atinux** [comment]
Any news about it?

**Comment by pi0** [comment]
> Also please note that these classes are only available since Node v10, might be an issue.

I think so as well. Maybe we should either drop node 8 support or check if `URL` is not undefined and otherwise fallback to https://www.npmjs.com/package/whatwg-url?

**Comment by posva** [comment]
@pi0 do you still need this one to go forward? If yes, we would have to make sure it works with node 8 since Vue 2 still supports that version of node even though it is unmaintained

**Comment by pi0** [comment]
@posva I think we can close it to avoid breaking changes and let userland to polyfill. We can also conditionally add to context only if node.js version supports it like:

```js
URL: typeof URL === 'undefined'  ? undefined : URL
```

**Comment by posva** [comment]
Okay, thanks a lot!

**Comment by lzxb** [comment]
Has this been released?
https://github.com/vuejs/vue/blob/dev/src/server/bundle-renderer/create-bundle-runner.js#L9

I see the source code of this address. I don't see the merge

**Pull request closed without merging**
