### PR TITLE
chore: fix injection warning typo

### PR DESCRIPTION
**Pull request by HusamIbrahim**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: fix typo

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by posva** [comment]
Thanks but this is right, we are talking about the injected values in the provided component

**Comment by HusamIbrahim** [comment]
@posva Yes I do understand that. But in this case the component you're refering to would be **_providing_** the value to be injected, whereas the value itself is _provided_. Even the [example code in the API docs](https://vuejs.org/v2/api/#provide-inject) says this .. 

```
// parent component providing 'foo'
var Provider = {
  provide: {
    foo: 'bar'
  },
  // ...
}
```

**Comment by posva** [comment]
but we are talking about the component that does the `inject: []`, the provided component.

**Comment by HusamIbrahim** [comment]
> but we are talking about the component that does the `inject: []`, the provided component.

You are totally right! I misunderstood the intention of the warning message 😁

**Pull request closed without merging**
