### PR TITLE
fix(#9361): appear error when using inline-template with no children

### LINKED ISSUE #9361: Warn when using inline-template attribute but no children
### Version
2.5.22

### Reproduction link
[https://codesandbox.io/s/r71q8py7mp](https://codesandbox.io/s/r71q8py7mp)

### Steps to reproduce
Open https://codesandbox.io/s/r71q8py7mp and read console log

### What is expected?
Don't execute following code from `genInlineTemplate` when `el.children.length !== 1 || ast.type !== 1` is true because `ast` is undefined.

```
function genInlineTemplate (el, state) {
    var ast = el.children[0];
    if (el.children.length !== 1 || ast.type !== 1) {
      state.warn(
        'Inline-template components must have exactly one child element.',
        { start: el.start }
      );
    }
    if (ast.type === 1) {
      var inlineRenderFns = generate(ast, state.options);
      return ("inlineTemplate:{render:function(){"   (inlineRenderFns.render)   "},staticRenderFns:["   (inlineRenderFns.staticRenderFns.map(function (code) { return ("function(){"   code   "}"); }).join(','))   "]}")
    }
  }
```

### What is actually happening?
Executing

```
 var inlineRenderFns = generate(ast, state.options);
      return ("inlineTemplate:{render:function(){"   (inlineRenderFns.render)   "},staticRenderFns:["   (inlineRenderFns.staticRenderFns.map(function (code) { return ("function(){"   code   "}"); }).join(','))   "]}")
```

### PR DESCRIPTION
**Pull request by Kermit-Xuan**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

add a dev-only warning for inline-template with no children.

### CODE REVIEW

**Comment by Kermit-Xuan** [comment]
@posva [#9361](https://github.com/vuejs/vue/issues/9361)

**Comment by Kermit-Xuan** [comment]
@posva

**Comment by posva** [comment]
You don't need to ping me like that. I'm already tracking activity in this repo 😄

**Comment by Kermit-Xuan** [comment]
> You don't need to ping me like that. I'm already tracking activity in this repo 😄

Can you tell me why `test-ssr-weex` isn't passed?

**Comment by posva** [comment]
I actually don't know, I don't work on weex

**Comment by yyx990803** [comment]
Thanks for the PR, it is unnecessary to change files in `packages` because they are auto-generated. The only files that need to be modified are in `src`.

I've merged #9365 which fixes the same issue but has tests.

**Pull request closed without merging**
