### PR TITLE
fix(props): consider prop types order for default bool value

### LINKED ISSUE #7485: Multi-type props defined without value gets empty string, should be true [Boolean, String]
### Version
2.5.13

### Reproduction link
[https://jsfiddle.net/realcarbonneau/68w22cbo/](https://jsfiddle.net/realcarbonneau/68w22cbo/)

### Steps to reproduce
Define a multi-type Boolean and String Prop, call the component by specifying the prop name (without a value).

### What is expected?
Prop contains true (Boolean type)

### What is actually happening?
Prop contains an empty string

---
The sequence does not change the result, both `[Boolean, String]` and `[String, Boolean]` give the same result.  The version does not change the result either (vue version 1.0.12, 2.2.1, edge on jsfiddle)

### PR DESCRIPTION
**Pull request by ArStah**
Fix #7485

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by ArStah** [comment]
Can i know, why there is no any action? Maybe i've made something wrong?

**Comment by posva** [comment]
Hey sorry for the delay, it went under my radar 😄 
Could you add a test, please?

**Comment by ArStah** [comment]
@posva done ;)

**Comment by ArStah** [comment]
Anyone alive there?

**Comment by mariolamacchia** [comment]
Hey there! Does this PR require more work to do? I'd love to have these changes deployed 🙂

**Comment by yyx990803** [comment]
Thanks for the PR, I will be doing final reviews/merging of outstanding PRs next week, please be patient.

**Comment by yyx990803** [comment]
Thanks again for the PR. There is an edge case not taken into account in this fix - that the Vue runtime might run in a different document from the app's code (see https://github.com/vuejs/vue/blob/dev/src/core/util/props.js#L178-L186)

I implemented a similar logic in 81e1e47c which fixes the original issue.

**Pull request closed without merging**
