### PR TITLE
enable style merge behavior between parent-child components (fix #3997)

### LINKED ISSUE #3997: Overwriting "style" attribute [Vue 2.0]
Hello,

With Vue 1 "style" attribute is "merged", but with Vue 2 it is completely overwritten. Is this by design?

In the following jsfiddle, if you remove "style" attribute it will then apply "style" from within component definition. As long as "style" is present on "<my-car>" (from main HTML window), it will completely overwrite component's style:
https://jsfiddle.net/rstoenescu/t0kb6vyu/2/

Thanks!

### PR DESCRIPTION
**Pull request by defcc**
fix #3997

Style priority orders as bellow:
1. binding style > static style.
2. parent style > child style.

### CODE REVIEW

**Comment by defcc** [comment]
Something wrong with background-image parsing. I'll update it later.

**Comment by defcc** [comment]
Will use a regexp to parse if background property included.

```css
background:url(http://xxx.jpg);
background-image:url(data:image/webp;base64,UklGRkoAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAwAAAARBxAR/Q9ERP8DAABWUDggGAAAABQBAJ0BKgEAAQAAAP4AAA3AAP7mtQAAAA==)
```

**Comment by defcc** [comment]
Will use a regexp to parse if background property included.

```css
background:url(http://xxx.jpg);
background-image:url(data:image/webp;base64,UklGRkoAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAwAAAARBxAR/Q9ERP8DAABWUDggGAAAABQBAJ0BKgEAAQAAAP4AAA3AAP7mtQAAAA==)
```

**Comment by yyx990803** [comment]
Thanks! There are a few places where I think there could be some perf improvement, but it's a bit hard to explain so I'll merge and tweak.

**Comment by defcc** [comment]
Thanks @yyx990803 ，I'll take a look.

**Pull request merged**
