### PR TITLE
support `for with` in template

### PR DESCRIPTION
**Pull request by gebilaoxiong**
issue: https://github.com/vuejs/vue/issues/5269

### CODE REVIEW

**Comment by rhyek** [comment]
Hey, thanks for doing this. One observation:

```js
  it('render with scope', () => {
    const vm = new Vue({
      data: {
        pos: [0, 2],
        list: ['a', 'b', 'c']
      },
      template: `
        <ul>
          <li v-for="i in pos" with="list">{{list[i]}}</li>
        </ul>
      `
    }).$mount()
    expect(vm.$el.textContent).toMatch('ac')
  })
```
That looks the same as:
```js
  it('render with scope', () => {
    const vm = new Vue({
      data: {
        pos: [0, 2],
        list: ['a', 'b', 'c']
      },
      template: `
        <ul>
          <li v-for="i in pos">{{list[i]}}</li>
        </ul>
      `
    }).$mount()
    expect(vm.$el.textContent).toMatch('ac')
  })

```
Only difference is the omission of `with`. The idea, really, is for `with` to provide something that is computed and doesn't currently exist on the vm.

**Comment by gebilaoxiong** [comment]
@rhyek Sorry, my unit test is wrong

**Comment by HerringtonDarkholme** [comment]
Thanks for your contribution.

But I'm afraid this breaks vue-loader. Vue loader will `stripWith` in production build to get rid of `with` syntax. 

Now it is done by prefixing `vm` to properties used in template, because almost every name in template can be found on Vue instance. 

However, this pull request breaks the assumption. And there is no easy way to tell where a name come from, scope or vm?

**Comment by posva** [comment]
imo It's better not to add more efforts to this feature yet, because atm we're not likely to add it

**Comment by gebilaoxiong** [comment]
@posva  Okay, I turned it off

**Comment by nickmessing** [comment]
@gebilaoxiong, and `use strict` doesn't allow `with` :(

**Comment by gebilaoxiong** [comment]
@nickmessing Perhaps we can add a prefix to avoid this problem, link `{{$scope.person.xxx}}`, but not important. **HerringtonDarkholme** is right.

**Pull request closed without merging**
