### PR TITLE
Propose an e2e testing framework

### PR DESCRIPTION
**Pull request by miherlosev**
Hello
I am a developer from the [TestCafe](https://github.com/DevExpress/testcafe) team.
In your [article on Medium](https://medium.com/the-vue-point/vue-in-2016-8df71d98bfb3#.bjcka9pet),
you mentioned that you have plans to improve the test story.

We want to propose TestCafe as an official testing tool for the Vue ecosistem.
Our e2e testing framework is a pure node.js solution, so it can easily integrate with Vue.

In this pull request, I rewrote all e2e tests using TestCafe to demonstrate key features, such as:

-  clean code (no 'waitForElementVisible', no waiting for page loads and xhr requests)
-  no need for additional dependencies, configs and browser plugins
-  easy setup
-  ES2016 syntax
-  flexible selectors

We would be happy to cooperate with you and we are ready to create vue-specific features (similar to Protractor selectors for Angular).

What do you think about it?

### CODE REVIEW

**Comment by yyx990803** [comment]
@miherlosev thanks a lot for the PR! I've been interested in testcafe since it was announced and was waiting for it to mature a bit. Before I can make a decision, I'll need to play with it a bit more in some other existing projects to get some first hand experience with it, but this PR is very helpful in that regard. Will get back to this after I test it more!

**Comment by miherlosev** [comment]
I have updated to the latest version 0.12.1. 
This version contains a lot of new features and bug fixes.
For details, see https://devexpress.github.io/testcafe/blog/testcafe-v0-12-0-released.html

**Comment by miherlosev** [comment]
We found that people start using testcafe for vue-based applications.
We wanted to give them the capability to test vue markup and component properties together.
To this end, we've created the [vue selector extentions](https://github.com/DevExpress/testcafe-vue-selectors).
Please, take a look and let us know what you think about it.

**Comment by miherlosev** [comment]
Since version 0.14.0 TestCafe supports the `file` schema and relative paths for the page directive. 
So, I removed the `http-server` module from `package.json` and changed all tests to relative paths.

**Comment by yyx990803** [comment]
Hey - really thanks for starting this PR and sticking with us, and sorry for letting this stand for so long. The truth is, over the time our need for e2e testing in the core repo itself hasn't really changed much, and we haven't found much benefit in changing our setup to a different tool. I'm sure there are certain things that TestCafe does better than what we are using, but in our use case (the core repo), we just want to avoid the cost of having learn a different API without substantial benefits. IMO, the better to promote TestCafe to Vue users would be creating examples of testing actual projects instead of the core repo.

**Pull request closed without merging**
