### PR TITLE
Uses reactive set to change a synced property

### PR DESCRIPTION
**Pull request by sunyatasattva**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:

Small improvement

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

**Other information:**

I'm using the reactive setter to set a property with the `sync` modifier. My case is that since the `sync` modifier is basically just syntactic sugar to avoid some boilerplate, it is useful for most case to set a property through `Vue.set`.

I might be wrong, but instead of opening an issue I thought doing a pull request would be faster, since the change is just a line of code.

### CODE REVIEW

**Comment by posva** [comment]
Hello thanks for your PR but using `Vue.set` has an extra cost because it forces Vue to add watchers whereas doing a plain assignment don't. This is intentional, remember every data property should be declared in `data`

**Comment by sunyatasattva** [comment]
Hey! Thanks for answering. I was just wondering if basically anything with `.sync` isn't practically expected to be reactive, and that would save some boilerplate.

But if you disagree, feel free to close of course :)

**Comment by posva** [comment]
Sync is for two way binding. You shouldn't do Vue. Set everyone to se something, it's for Vey specific cases. Look for caveat in the documentation. That would hopefully clarify many things

**Comment by yyx990803** [comment]
This seems unnecessary to me, since the event listener would only be created if the key already exists in that object. This would only apply when the key exists and is not already reactive, which sounds like quite an unlikely case for `v-bind` object. Closing but feel free to provide a use case where this would prove necessary.

**Pull request closed without merging**
