### PR TITLE
improve examples html title

### PR DESCRIPTION
**Pull request by kazupon**
NOTE:
  consistently keep the examples of vuejs.org.
  https://vuejs.org/v2/examples/

### CODE REVIEW

**Comment by Relucent** [comment]
+ examples （paging component ）

**Review by judyburgett3 — COMMENTED** [review]
Thank you for the help

**Comment by judyburgett3** [comment]
thank you

**Comment by judyburgett3** [comment]
keep going

**Comment by judyburgett3** [comment]
we are doing it

**Comment by judyburgett3** [comment]
thanks again for the help

**Comment by judyburgett3** [comment]
I just hope I am doing it right

**Pull request merged**
