### PR TITLE
Use more serious strings in tests

### PR DESCRIPTION
**Pull request by phanan**
As discussed, this commit aims to make some tests a bit more serious by replacing `'hi hi ho ho'` with `'foo bar'` :)

### CODE REVIEW

**Comment by azamat-sharapov** [comment]
I liked previous version soooo much better than this "serious" one.. This is open source.. why so serious? :)

**Comment by yyx990803** [comment]
Well, it's good to have some consistency for dummy text usage :) The e2e tests seem to be failing though.

**Comment by phanan** [comment]
Ok that's weird:

image

Let me check again.

**Comment by phanan** [comment]
@yyx990803 I think this is not a problem with my code per-se. @chrisvfritz is having the same problem with the two `e2e`.

**Comment by chrisvfritz** [comment]
@phanan I'm only experiencing the issue with the updated phantomjs binary though (in phantomjs-prebuilt). :confused:

**Comment by azamat-sharapov** [comment]
Let's just keep sourcecode fun, as it is :smile:

**Comment by yyx990803** [comment]
@azamat-sharapov I'd like to keep it fun, but also consider Vue's adoption in the more "serious" world :)

That said, @phanan is pretty good at writing humorous comments, so maybe we can squeeze some of those in in the future.

**Pull request merged**
