### PR TITLE
fix(compiler): Remove the waring for valid v-slot value

### PR DESCRIPTION
**Pull request by liximomo**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

The Vue doc says that one can use destructuring props with fallback value as v-slot's value.
image

Actually, this will cause a warning.
image

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by yyx990803** [comment]
Nice catch, although I think the proper fix would be introducing an extra branch for `v-slot` and check whether the expression is valid in a function argument position.

**Comment by liximomo** [comment]
@yyx990803 I'm glad to implement this.

**Comment by yyx990803** [comment]
I just fixed CI - could you  rebase against `dev`? Thanks.

**Comment by liximomo** [comment]
@yyx990803 Done.

**Pull request merged**
