### PR TITLE
test: test bundle size

### PR DESCRIPTION
**Pull request by ai**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

[size-limit](https://github.com/ai/size-limit) is a tool to show how many kilobytes your JS library increases the user bundle. You can set size budget and size-limit will prevent JavaScript libraries bloat on Travis CI.

It already used in Autoprefixer, PostCSS and JSS. For instance, I reduce Logux Client size 2x because I found some unexpected huge dependencies.

For Vue this tool can be useful to always know project size and prevent unexpected size regression.

### CODE REVIEW

**Comment by posva** [comment]
Thanks for the pr Andrey 🙂 
I'm not sure this is useful for Vue because it doesn't have any dependency and also because we use rollup for bundling. The tools looks interesting, really like the fact that you added a way to run the bundle analyzer

**Comment by ai** [comment]
@posva yeap, tool is much effective in project with dependencies :D.

But even without dependencies some wrong `process` usage could increase bundle size for few KB.

Anyway, Vue is already small, so it is up to you, to lint bundle size or not :)

**Comment by ai** [comment]
@posva BTW, React is planning to add this kind of tool too https://github.com/facebook/react/pull/10090

But since you have no dependencies and already build-in file, maybe `bundlesize` by @siddharthkp will be better for you. It doesn’t run webpack, so results is not so accurate, but in other hand tool works faster.

**Comment by posva** [comment]
@ai I see, yeah, bundlesize may be useful since it checks a generated file but lets you generate it as you want

**Comment by yyx990803** [comment]
Hey thanks for the PR @ai - in fact, Vue's build script already logs the size for every dist file when they are built, and we don't have any dependencies, so I believe an extra tool is unnecessary.

**Pull request closed without merging**
