### PR TITLE
Fixed typos.

### PR DESCRIPTION
**Pull request by bringtree**

### CODE REVIEW

**Comment by bringtree** [comment]
@yyx990803 Would you help to review this? Thank you in advance.

**Comment by posva** [comment]
Thanks for the PR @bringtree!
The files inside the `packages` folder are auto-generated and should not be changed. Can you please reset those back and modify the corresponding source files?

**Comment by bringtree** [comment]
Sorry, I will do it after class.

**Comment by bringtree** [comment]
Sorry, I will do it after class.@posva

**Comment by posva** [comment]
No worries 😉  Thanks

**Comment by bringtree** [comment]
sorry, i can't deal with it. i can't understand the codes. i think i should learn JS harder.

**Comment by bringtree** [comment]
@posva I have updated the pull request,  may you take a look when you are available, thank you!

**Comment by posva** [comment]
@bringtree thank you. I'm checking it now

**Pull request merged**
