### PR TITLE
fix: convert emits to props, fix #13104

### LINKED ISSUE #13104: Vue 2.7 strictTemplates error
https://github.com/xiaoxiangmoe/issue-vue-2.7-on-click-type-error.git

```
pnpm run type-check
```

```
src/App.vue:12:6 - error TS2559: Type '{ onClick: any; }' has no properties in common with type 'Readonly<Partial<{}> & Omit<Readonly<ExtractPropTypes<{ border: { type: PropType<boolean>; }; }>>, never>>'.

12     <HelloWorld @click="handleClick" />
        ~~~~~~~~~~


Found 1 error in src/App.vue:12
```

---
HelloWorld.vue
```vue
<script setup lang="ts">

interface ButtonProps {
    border?: boolean; 
}

const props = defineProps<ButtonProps>() 
defineEmits<{
    (event: 'click',payload: MouseEvent): void
}>()
</script>
<template>
    <div id="app">
        <button @click="$emit('click', $event)">Click me</button>
    </div>
</template>
```

This error come since vue-tsc 1.7.12

### PR DESCRIPTION
**Pull request by so1ve**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix: fixes #13104
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch for v2.x (or to a previous version branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

Converts emits to props.

**Other information:**

### CODE REVIEW

**Comment by yyx990803** [comment]
@so1ve I tested this locally and it doesn't seem to fix #13104 - is this something you still intend to work on? We might be able to get this in the final patch release before EOL.

**Comment by so1ve** [comment]
I'll take a look and add tests

**Comment by so1ve** [comment]
This fix is beyond my capabilities and I hope someone else can fix it.

**Comment by zcf0508** [comment]
> @so1ve I tested this locally and it doesn't seem to fix #13104 - is this something you still intend to work on? We might be able to get this in the final patch release before EOL.

#13133

https://github.com/vuejs/vue/pull/13133/files#diff-d26123bca327fbaf4e0ce33d7085fcaf9f4a39be4f76a1d0c15e0843afb1af9fR153

Maybe this is the key line to resolve the error of #13104

**Comment by so1ve** [comment]
No, your implementation doesn't take `extends` and `mixin` into account

**Comment by zcf0508** [comment]
> No, your implementation doesn't take `extends` and `mixin` into account

Yes, you are right, I'm working on it. But now I have some questions. I see you add a test that you can get `emit` functions from`props` in `setup` function, but the `props` does not expose those functions. It is a right type test?


image

image

**Comment by so1ve** [comment]
Yes, because it can be `undefined`

**Comment by zcf0508** [comment]
Does it mean that If a component use `props.onFoo` in runtime, the function will never work? Is the `onFoo` only used for type inference?

**Comment by so1ve** [comment]
Yes, seemed to be true

**Comment by zcf0508** [comment]
image

https://github.com/vuejs/vue/pull/13133

I think it works with extends and mixin now.

**Pull request closed without merging**
