### PR TITLE
Add "Support Ukraine" badge in README

### PR DESCRIPTION
**Pull request by vasylnahuliak**
## Summary

This Pull Request is aimed at helping Ukrainian Army get necessary funding in time of open-scale war with Russia by providing link to official international account created by National Bank of Ukraine.

## Changelog:

[General] [Added] - Add badge with link to National Bank of Ukraine's website

## Test Plan

Badge image: 
155879304-107042dc-005c-4ea9-9967-dc05881c35e4

**What kind of change does this PR introduce?**

- [x] Other, please describe: Add "Support Ukraine" badge in README

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by SAprelov** [comment]
No politics, please.

**Comment by Janlaywss** [comment]
No politics, please. 😡😡😡

**Comment by Janlaywss** [comment]
No one wants war, and no country wants others to have missiles on their doorsteps.

I sympathize with the suffering of ordinary people in Ukraine, But the Ukrainian government has made a choice and must bear the corresponding price.

I don't think the open-source community should get involved in politics.

**Comment by 0x219** [comment]
No one wants war, and no country wants others to have missiles on their doorsteps.

I sympathize with the suffering of ordinary people in Ukraine, But the Ukrainian government has made a choice and must bear the corresponding price.

I don't think the open-source community should get involved in politics.

**Comment by q1uxu** [comment]
hope the world peace

**Comment by yyx990803** [comment]
As an individual, I deeply sympathize with what the Ukrainian people are going through and wish nothing but peace and safety for Ukraine. I have personally expressed support on Twitter, and many Vue team / community members have done the same. However, I do not want Vue, an OSS project, to become a vehicle for political messages. We will do what we can as individuals, but not under the name of the project.

**Pull request closed without merging**
