### PR TITLE
fix #4344 #4445 #4511

### LINKED ISSUE #4344: Error parsing regular expression
Error: Parsing file /wireframes/node_modules/vue/dist/vue.common.js: Line 6278: Invalid regular expression

I get a parse error, these seem to be the offending lines.

```
var defaultTagRE = /\{\{((?:.|\n)+?)\}\}/g;
var regexEscapeRE = /[-.*+?^${}()|[\]/\\]/g;

var buildRegex = cached(function (delimiters) {
  var open = delimiters[0].replace(regexEscapeRE, '\\$&');
  var close = delimiters[1].replace(regexEscapeRE, '\\$&');
  return new RegExp(open + '((?:.|\\n)+?)' + close, 'g')
});

```

### PR DESCRIPTION
**Pull request by arielpchara**

### CODE REVIEW

**Comment by arielpchara** [comment]
fix regular expression

**Comment by posva** [comment]
That's weird, there's no need to escape `/` inside `[]`

**Comment by arielpchara** [comment]
Using browserify show that error
Error: Parsing file node_modules\vue\dist\vue.common.js: Line 6597: Invalid regular expression
Browserify use stream to concat files

**Comment by yyx990803** [comment]
This is technically a bug in whatever parser Browserify uses to parse modules (maybe an old version of Acorn), but I guess we'll just merge this to make it work...

**Pull request merged**
