### PR TITLE
Add the runtime-only warning for el in-DOM HTML template

### PR DESCRIPTION
**Pull request by KingMario**
Make the warning more explicit for template complier.
Plus, el option which will be used to extract the template should also emit the warning.

### CODE REVIEW

**Comment by posva** [comment]
`el` is also used in runtime only:

```js
new Vue({
  el: '#app',
  render: h => h(App)
})
```

**Comment by KingMario** [comment]
@posva, The warning is emitted when there's no render function (handwritten or compiled), so it's no problem whether `el` is used or not in runtime only.

**Comment by posva** [comment]
@KingMario You're right, I didn't look the code above and thought this warning was a different one (`Failed to mount component: template or render function not defined`)

**Comment by posva** [comment]
Can you add a test then, please?

**Comment by KingMario** [comment]
The tests passed in my local build.
Have no idea.

**Comment by KingMario** [comment]
Added npm run build in ci.sh.
But don't know whether it's acceptable.

**Comment by posva** [comment]
@KingMario I just realised there're no tests for that, sorry. I removed the extra commits and added a check for `el`

**Pull request merged**
