### PR TITLE
feat(v-model): add lazy modifier for v-model on components(close #6914)

### LINKED ISSUE #6914: Request: add v-model.lazy for components
### What problem does this feature solve?
v-model for components already supports .trim and .number.
Lazy modifier support for components would make it more uniform across the platform.

### What does the proposed API look like?
The only change (backwards compatible) would be to add a new property to model definition:
```
model: {
  prop: 'value',
  event: 'input',
  eventLazy: 'change'
}
```

### PR DESCRIPTION
**Pull request by javoski**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

**Other information:**
close #6914 .

### CODE REVIEW

**Comment by rstoenescu** [comment]
Any news on this? Is it going to get merged, and if so, when is it scheduled to get into an official release? Thanks.

**Comment by posva** [comment]
@javoski  I think adding this feature should allow **both** using `v-model` and `v-model.lazy`, and therefore, a component could potentially have 2 different events for model

---

On a side note, this is possible with a prop on the component

```vue
<my-comp v-model="value" lazy/>
```

```vue
// my-comp.vue
<input :value="value" @inpu="$emit('input', $event.target.value)" v-if="lazy" />
<input :value="value" @change="$emit('input', $event.target.value)" v-else />
```

or with a render function as well http://jsfiddle.net/dazvtwat/

I do agree to have `.lazy` makes it more succinct though 🙂

**Comment by javoski** [comment]
@posva Yeah, it's reasonable for components to aware of if they are using `.lazy` modifier on `v-model`, and prop is a proper way. 
But in the case of single input element wrapper component, I prefer to do like this:
```js
const MyComp = {
  ...
  template: `<input :value="value" @input="onUpdate" @change="onUpdate">`,
  methods: {
    onUpdate (e) {
      this.$emit(e.type, e.target.value)
    }
  }
}
```

**Comment by posva** [comment]
That's much better, indeed, completely forgot about `event.type` 😄 
But we should allow the user to customize both, `input` and `change` events name emitted by the component because the component can be used in both scenarios but only one event name can be provided, and if it is provided, it will end up used by both `v-model.lazy` and `v-model`

**Comment by tmorehouse** [comment]
It would be nice for a component to actually know if the `v-model` is requesting a `lazy` (in some cases this may be required).

Native inputs will have `element._vModifiers` set with an object defining what modifiers are in use (i.e. `{ lazy: true, trim: true }`, while the root element of a component will have `this.$el.vModifiers` set to an empty object, regardless of modifiers in use.  It would be very handy to have these values made available to components (or maybe exposed as a readonly `this.$vModifiers` injection, although the former would be easier to implement)

**Comment by Tantawi** [comment]
@javoski Can you please look at the merge requests and try to get this merged? thanks a lot!

**Comment by Sshuichi** [comment]
@PhilipJohnBasile Please mege? :3

**Comment by Tantawi** [comment]
@javoski Awesome now that it is approved, can you please look at the conflicts and merge? thanks a lot!

**Comment by PhilipJohnBasile** [comment]
There's merge conflics @Tantawi

**Comment by cn-xufei** [comment]
Exciting. When can we merge?

**Comment by javoski** [comment]
This PR is too old, so I opened a new one based on the latest codebase. #11830.

**Pull request closed without merging**
