### PR TITLE
visiblity modifier for v-show

### PR DESCRIPTION
**Pull request by crswll**
I saw #2382 and figured I'd give contributing a shot. I'm almost certain I followed the guidelines but if I didn't let me know.

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks @crswll - sorry I didn't communicate this clearly, I didn't think adding a modifier to `v-show` was the best way to approach this. What he wanted can simply be solved by using a CSS class to toggle the element's opacity with CSS transitions.

**Comment by simplesmiler** [comment]
I asked https://github.com/vuejs/vue/issues/2382#issuecomment-188131890 because `opacity: 0` and `visibility: hidden` do not produce identical results. Namely, content with `opacity: 0` is interactive (links and buttons can be clicked, inputs are focusable), while content with `visibility: hidden` is not.

`opacity: 0; pointer-events: none` produce similar result to `visibility: hidden`, but only works in IE11+.

Thus I believe a directive for toggling `visibility` instead of `display` is handy, either in core or in ecosystem.

**Comment by crswll** [comment]
Ah I got you. I was just thinking in terms of getting the transitions right. Honestly I was just kind of bored and wanted to see if I can do it!

**Comment by yyx990803** [comment]
@simplesmiler ah that's true. That's why I exposed the transition API though. With that you can easily write your own `v-visible` directive.

**Comment by milesingrams** [comment]
I've been trying to write a v-visible directive that triggers transitions and I cant see any way to trigger enter/leave transitions without importing directly from 'vue/src/platforms/web/runtime/modules/transition'.
You mentioned exposing the transition API but I cant see any place to import it! Where might I find this exposed transition api?

**Pull request closed without merging**
