### PR TITLE
Allow tag selectors in render functions

### PR DESCRIPTION
**Pull request by shreeve**
This allows tags such as `section.active.admin@intro`, which would yield `<section class='active admin' id='intro'>`.

Allowing these types of selectors, when used in combination with another tiny enhancement (https://github.com/shreeve/coffeescript/pull/1) to `CoffeeScript` allows us to write native `CoffeeScript` that looks a lot like `JSX`, but is actually full fledged `CoffeeScript`. Here's an example of something we're working on (a work in progress, but coming along!):

conversation coffee lite 2016-10-22 23-08-41

### CODE REVIEW

**Comment by phanan** [comment]
If I get this right, I don't think this belongs to the core. Maybe a custom `render` function is what it should be.

**Comment by shreeve** [comment]
A custom render function would work. Is there a way to have a hook inside of createElement that is able to invoke this code if specified?

**Comment by HerringtonDarkholme** [comment]
I guess you can. `Vue.mixin({created() {this.$createElement = customCreateElement}})` should works. Also `Vue.prototype._h` should also be overridden.

**Comment by shreeve** [comment]
Oh, man! That's great.

Is this a one-liner type of tweak that we could put in our top-level app and everything would inherit? That would make it super easy. Is there another library, module, or mixin (or whatever else) that could be used as an example for this type of feature?

**Comment by HerringtonDarkholme** [comment]
> Is this a one-liner type of tweak that we could put in our top-level app and everything would inherit?

Yes, if I read the code correct. Place it in your entry file and most things will be fine.

> Is there another library, module, or mixin (or whatever else) that could be used as an example for this type of feature?

I don't know. I think this is too hacky to be included in a project's README...

**Comment by shreeve** [comment]
@phanan - Is there already a way to support such as custom render function as a Vue plugin?

**Comment by phanan** [comment]
As it has turned into a discussion, I'd suggest opening a thread on [the forum](http://forum.vuejs.org) instead.

**Pull request closed without merging**
