### PR TITLE
warn when overwrite built-in directives (#4876)

### PR DESCRIPTION
**Pull request by gebilaoxiong**
https://github.com/vuejs/vue/issues/4876

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by dsonet** [comment]
IMO it's not necessary to detect this. Kinda like to detect if someone overwrite the Vue instance.
And if really really needs, should only in development mode.

**Comment by gebilaoxiong** [comment]
@dsonet thanks for you reply.

https://vuejs.org/v2/guide/custom-directive.html#Intro

> In addition to the default set of directives shipped in core (v-model and v-show), Vue also allows you to register your own custom directives

Like `checkComponent()`, I was checking in development mode

**Comment by yyx990803** [comment]
Hmm thanks for the PR - bt this doesn't seem to detect cases where user attempts to register other built-ins e.g. `v-if` (which would just fail silently).

After thinking about it, it seems the only way would be to have a constant list of built-ins for each platform. Feels too much of an edge case for this extra maintenance burden.

Still, thank you for the effort put into this PR!

**Comment by gebilaoxiong** [comment]
Yes, it is also bothering me, in addition also need to distinguish between compile-time and runtime

**Pull request closed without merging**
