### PR TITLE
allow functional components to return multiple VNodes (fix #8191)

### LINKED ISSUE #8191: typescript types don't allow multi-root functional components
### Version
2.5.16

### Reproduction link
[https://github.com/zevdg/vue-typescript-multi-root-component](https://github.com/zevdg/vue-typescript-multi-root-component)

### Steps to reproduce
npm run serve

### What is expected?
there shouldn't be errors

### What is actually happening?
The page runs and works as expected, but the build shows type errors because the type definitions specify that a single VNode is always returned from functional componnts' render functions.

---
The fix for this is trivial.  I've already fixed it locally, and I'll make a pull request.

### PR DESCRIPTION
**Pull request by zevdg**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by zevdg** [comment]
fixes #8191

**Comment by zevdg** [comment]
Silly me.  I assumed that since vue was preliminary a Javascript project, it wouldn't have the typescript toolchain installed, and therefor wouldn't be able to test the types.  I'll add a test for this to `yarn test:types`.

**Comment by HerringtonDarkholme** [comment]
@ktsn  @LinusBorg Is this a public API ? I checked the doc here https://vuejs.org/v2/api/#render and here https://vuejs.org/v2/api/#render. But it seems nowhere mentions multiple root.

**Comment by zevdg** [comment]
The most official source I've seen on the topic has been a core team member here suggesting it as an option at https://github.com/vuejs/vue/issues/7088#issuecomment-345855657

Given that articles like https://zendev.com/2018/05/07/multi-root-vue-components.html are starting to pop up, it probably ought to be added to https://vuejs.org/v2/guide/render-function.html#Functional-Components.  I'm surprised it wasn't already.

**Comment by chrisvfritz** [comment]
Oh, I thought I did mention it. I'll add it. 👍

**Comment by zevdg** [comment]
is there anything holding  this up?

**Comment by zevdg** [comment]
poking this again, is there anything else I need to do to get this merged?

**Comment by LinusBorg** [comment]
Please be patient, we are currently wrapping up work on other core projects and will return attention back to the core repository shortly.

**Comment by zevdg** [comment]
No worries.  Thanks for the update :-)

**Comment by destructive-dragon** [comment]
3 months later, what's holding this up?

**Pull request merged**
