### PR TITLE
Methods in functional components

### PR DESCRIPTION
**Pull request by hirokiosame**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Currently it's difficult to use the functional template since you lose access to closures where as the render method can reference closed-over functions.

### CODE REVIEW

**Comment by Kingwl** [comment]
why `functional` component need method?

**Comment by hirokiosame** [comment]
@Kingwl I already explained in the PR body but, when using a render method instead of using a functional template, I can write functions outside of the component and reference them via closure. However, when using a template, I no longer have access to the closure.

I can reference them via `$options.methods` but seems hacky and would prefer official support in offering a similar API to stateful components.

**Comment by Kingwl** [comment]
I respect your work, but I think there will be a better solution
/ cc: @posva

**Comment by hirokiosame** [comment]
Here's an issue in vue-loader (it was originally in vue but closed) that might explain the use-case more clearly: https://github.com/vuejs/vue-loader/issues/1291

What are you thinking @Kingwl ?

**Comment by yyx990803** [comment]
I don't think we should be going further along the route of "making functional components work like normal components in a Vue file", for the following reasons:

- In v3, stateful components are much faster to initialize, and this should make it less necessary to use functional components just for performance
- v3 stateful components can also return multiple root nodes

If we want to make functional components fully equivalent to stateful ones in a Vue file, we go down the rabbit hole of supporting components, directives, methods, provide/inject and all other options... which eventually defeats the simplicity of functional components. I think we should go back and make functional components more about "functions".

**Pull request closed without merging**
