### PR TITLE
Fix using one delay to control all transitions.

### PR DESCRIPTION
**Pull request by guidobouman**
Vue transitions have a wrong timing when having CSS like the following:

```
.[transition-name]-enter-active, .[transition-name]-leave-active {
  transition: opacity 0.8s ease, transform 0.7s ease;
  transition-delay: 0.4s;
}
```

Which in turn bubbles errors to the console. This PR fixes the bug.

I have a question though: Is parameter re-assign allowed in Vue? It's not configured in the ESlint setup.

### CODE REVIEW

**Comment by guidobouman** [comment]
Also, where'd I put a test for this? I assume after `custom-transition-classes` in `test/unit/features/transition/transition.spec.js`?

And should this actually be tested? As this seems like a niche thing to test.

**Comment by yyx990803** [comment]
Yeah, looks quite a niche to test. Could you please provide a fiddle so that I can confirm it though?

**Comment by guidobouman** [comment]
@yyx990803 https://jsfiddle.net/o8u35ywu/

**Comment by guidobouman** [comment]
Also, delays is never an empty array, so concat can't end up in an infinite loop.

To be sure we could add a fallback like `delays = delays.concat(delays || '0s')` But that would mean we need to know the syntax of a delay inside the function, which could cause issues when a browser decides to change the syntax.

**Comment by guidobouman** [comment]
@yyx990803 This should be mergeable, right?

**Comment by yyx990803** [comment]
Thanks!

**Pull request merged**
