### PR TITLE
Fix/change create event to event

### LINKED ISSUE #11953: Use CustomEvent instead of document.createEvent
### What problem does this feature solve?
Document.createEvent has been deprecated, it is recommended to use CustomEvent instead.

https://developer.mozilla.org/zh-CN/docs/Web/API/Document/createEvent

https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/directives/model.js#L141

### PR DESCRIPTION
**Pull request by answershuto**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Document.createEvent has been deprecated, it is recommended to use CustomEvent instead.

https://developer.mozilla.org/zh-CN/docs/Web/API/Document/createEvent

close #11953

### CODE REVIEW

**Comment by Justineo** [comment]
Thank you for your contribution! But it seems that the `CustomEvent` constructor doesn't work in IE:

https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Comment by answershuto** [comment]
Hi, @Justineo .details are not used, is it possible to use Event instead.

https://developer.mozilla.org/en-US/docs/Web/API/Event

**Comment by Justineo** [comment]
Though it's marked as deprecated, `createEvent` won't be removed and will continue to be supported by browsers. IMO we get little benefit from replacing it with the proposed implementation as currently it has been working fine for a long time.

**Comment by posva** [comment]
Thinks but we need IE support

**Pull request closed without merging**
