### PR TITLE
add beforeMove and afterMove hooks (#4885)

### PR DESCRIPTION
**Pull request by Kingwl**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by yyx990803** [comment]
This is cool, but Vue core cannot assume `Promise` is available :/

**Comment by Kingwl** [comment]
have we got some workaround for it? :xd

**Comment by yyx990803** [comment]
We will likely need a small shim for `Promise.all`... but it has to be tiny.

**Comment by Kingwl** [comment]
https://jsfiddle.net/vzj26vek/
could that resolve this problem?

**Comment by lonelyclick** [comment]
Maybe we can release `transition-group` as a package, just like react-addons-css-transition-group

**Pull request closed without merging**
