### PR TITLE
Add empty-to-undefined modifier to v-model

### LINKED ISSUE #3541: Add a v-model modifier to treat empty input values as null
The straightforward reason for this request is that there's currently no way to create an optional numeric field using v-model since empty inputs are reset to zero.

The fuzzier reason is that in many if not most models an empty input signifies the absence of its value, hence the error message "Please enter a username" instead of "Please enter a username that isn't empty," and the fact that, in contrast to data validation tools like JSON schema, HTML5 doesn't allow `required` fields to be empty.

I have no idea what this modifier should be called, though.

### PR DESCRIPTION
**Pull request by bopjesvla**
Fixes #3541. Still haven't come up with a better name.

### CODE REVIEW

**Comment by bopjesvla** [comment]
I have no idea what's up with those TodoMVC tests.

**Comment by bopjesvla** [comment]
this branch is now identical to base but checks still fail

**Comment by bopjesvla** [comment]
ok I'm done

**Comment by LinusBorg** [comment]
make sure to clear your npm cache, then run the tests again

**Comment by bopjesvla** [comment]
the CI runs every test on a brand new linux installation, right?

**Comment by LinusBorg** [comment]
CircleCI seems to cache dependencies, this hit me with a recent PR for vue-router: 

https://github.com/vuejs/vue-router/pull/641#issuecomment-245479682

clear your local cache and re-run them, if that works locally, I guess Evan can reset circleCI'S cache ?

**Comment by bopjesvla** [comment]
Cleared my cache and reinstalled, which resulted in yet another random test failing on the base branch (v-for with transitions iirc). I guess I'll just rollback my rollback and wait for the CircleCI reset.

**Comment by bopjesvla** [comment]
@yyx990803 Could you clear the CircleCI cache?

**Pull request closed without merging**
