### PR TITLE
fix(compiler): event handler with modifiers swallowing arguments

### LINKED ISSUE #10867: Multiple arguments in custom event with a modifier are not passed to handler
### Version
2.6.10

### Reproduction link
[https://jsfiddle.net/50wL7mdz/30115/](https://jsfiddle.net/50wL7mdz/30115/)

### Steps to reproduce
Add a modifier to one of the event listeners. e.g. @emission.once

### What is expected?
That all arguments will be passed to the function

### What is actually happening?
Only the first argument is passed

---
My guess is that it lies in the template compiler which creates a function($event){...}  and calling the handler with $event instead of ...arguments?

### PR DESCRIPTION
**Pull request by despreston**
Pass full parent argument list to the event handler when there are event
modifiers present.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

Fix #10867

### CODE REVIEW

**Comment by despreston** [comment]
Hm. This is kind of strange b/c I can successfully run the todomvc app using my build w/o issue. I'm not very familiar with nightwatch; perhaps someone with a better eye can help me debug this one.

**Comment by posva** [comment]
It's probably necessary to avoid the `spread` operator to support more browsers and use `apply` instead

**Comment by despreston** [comment]
@posva Thanks again!

**Comment by despreston** [comment]
@posva Do you know if there's a plan to push this into production soon? I'm actually being bit by this in a project now. The workaround works but obviously I'd prefer the solution I helped fix 😝.

**Pull request merged**
