### PR TITLE
feat(errors): sync/async error handling for lifecycle hooks and v-on handlers (#7653, #6953)

### PR DESCRIPTION
**Pull request by enkot**
- Added async errors handling for lifecycle hooks and event handlers (issue link: #7653). 

Update:
- Added normal and async errors handling in v-on handlers from @coldino (issue link: #6953).

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by coldino** [comment]
Can we add error handling for v-on handlers to this? Both sync and async need to be caught for them.

I have working code and tests for this here: <https://github.com/coldino/vue/commits/event-handler-errors>. It would need very minor updates to work with the changes in this PR.

**Comment by enkot** [comment]
@coldino 
I think it will be great to address 2 issues in this PR. But what will be the proper way to merge changes? You can create pull request to this branch - "feature/async-errors-handling". ( or just create separate PR for #6953 )

**Comment by coldino** [comment]
@enkot The changes will overlap significantly as I would switch to using your handlePromiseError function, so I will create a PR for your branch. Note that in addition to the ones you implemented, I also added async error handling for:
 * watcher callbacks
 * nextTick callbacks
 * invoked functions (v-on)
 * directive hooks

Currently there are only tests for the v-on invoked function async errors. I don't have enough experience with the testing system to add tests for all of them. If you are able to assist with this we can have much greater coverage for async error catching.

I will keep the hooks without tests in a separate commit so you can include/exclude as you choose.

**Comment by coldino** [comment]
I have only included the v-on checks in the PR as I didn't want to include changes with no tests and possibly delay this PR.

**Comment by vitormd** [comment]
What is holding this PR?
It's 3 months.

**Comment by humoyun91** [comment]
Does it support page level components which is not directly wrapped:
```
<ErrorBoundary>
  <router-view />
</ErrorBoundary>
```
I checked it with `Vue@2.7.10`, seems not working

**Pull request merged**
