### PR TITLE
memomize once util to remove extra let

### PR DESCRIPTION
**Pull request by miguelsolano**
removes a variable and memoizes the fn so that the var is no longer needed.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by posva** [comment]
If the same callback fn is passed to other libs that also add a `called` property to the function, this will not work as expected

**Comment by miguelsolano** [comment]
So would renaming the property to something more specific be an option or is this enough of a reason to warrant a close?

**Comment by yyx990803** [comment]
Thanks for the PR, however I think the closure variable is cleaner here (avoids polluting the passed function and avoids potential clashes).

**Comment by miguelsolano** [comment]
No worries! Makes sense! Still reading and studying the source, plenty of opportunities for a PR. :)

**Pull request closed without merging**
