### PR TITLE
Fix babel-plugin-transform-vue-jsx#74 (functional components with h auto-injection)

### PR DESCRIPTION
**Pull request by nickmessing**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Fixes the issue described in [babel-plugin-transform-vue-jsx#74](https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/74)

### CODE REVIEW

**Comment by posva** [comment]
Hey, the issue link is broken, can you get a working link please?

**Comment by HerringtonDarkholme** [comment]
The implementation looks good. 

It feels strange for me to injectt `_context` to a `this`-less functional component, though.
https://vuejs.org/v2/guide/render-function.html#Functional-Components

**Comment by nickmessing** [comment]
@HerringtonDarkholme, I am not sure why but we do have a unique context for each functional component anyway, and this change won't break anything. I actually think that if we have to have a context why not have a common context shared between all functional components since it's going to be "empty". @yyx990803, can you please share your opinion on that?

**Comment by yyx990803** [comment]
Hmm, indeed having `this` in a functional render fn feels weird. I think injecting this could be a bit surprising if users accidentally use it.

Since users have to use the `context` in most cases when using functional components, they have to provide `h` as the first argument anyway :/

Maybe instead - if the function name is `render` and have no arguments, we inject the `h` argument automatically?

**Comment by nickmessing** [comment]
@yyx990803, I think that should be discussed in an issue in the babel-plugin-transform-jsx itself.

**Comment by Gcaufy** [comment]
I get the same issue
`Cannot read property '$createElement' of undefined`

for some reason, `render` is injected to the component

**Comment by nickmessing** [comment]
@Gcaufy, can you please create an issue in vuejs/babel-plugin-transform-vue-jsx with all the information?

**Comment by shelune** [comment]
This occurred to me today and seems like having a method called `render()` inside the `methods` property will cause this error.

**Pull request closed without merging**
