### PR TITLE
Allow slot names to be numbers

### LINKED ISSUE #5480: `v-for` with named `slot` (via `v-for` index) skips first item for 0-based indices
### Version
2.2.6

### Reproduction link
[https://codepen.io/Rask/pen/GmZedP](https://codepen.io/Rask/pen/GmZedP)

### Steps to reproduce
See Codepen. Create a component with a `slot` repeated over `v-for` and `name`d with the index, then render the slot elements in the parent component using matching indices. Set the index to be `0..n` integers (i.e. a non-associative array).

### What is expected?
All elements that are rendered with `v-for` and slot index should be rendered properly from the parent component data.

### What is actually happening?
The very first element defined with `v-for` is somehow skipped when rendering.

---
I'm building a modular repeater field where you can add and remove items which are synced via basic events. The items are slotted in via item indices which are in sync by setting the slot index inside the custom component when rendered inside the parent.

Can this be related to 0-based indices or something? When I replace the `slot` `name` with `:name="'item' index"` the rendering works as expected.

### PR DESCRIPTION
**Pull request by posva**
Closes #5480

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by posva** [comment]
So flow is complaining about the `name` value being undefined inside of the if but I don't see how that's possible...

**Comment by yyx990803** [comment]
Well let's just make it `name: any`

**Comment by posva** [comment]
@yyx990803 That won't change the error, I should have posted it to make it clearer:

```
src/core/instance/render-helpers/resolve-slots.js:22
 22:       const slot = (slots[name] || (slots[name] = []))
                         ^^^^^^^^^^^ access of computed property/element. Computed property cannot be accessed with
 22:       const slot = (slots[name] || (slots[name] = []))
                               ^^^^ possibly uninitialized variable
```

**Comment by HerringtonDarkholme** [comment]
I guess this is caused by flow's wrong flow analysis. `name` is declared in outer block, not in the `name = child.data.slot`. In this case, flow might be confused about whether name will be changed. 

Changing to this will work
```ts
    if ((child.context === context || child.functionalContext === context) &&
        child.data && child.data.slot != null) {
      const name = child.data.slot
}
```

**Pull request merged**
