### PR TITLE
Check parentNode property before remove el from DOM

### PR DESCRIPTION
**Pull request by VincentGarreau**
Fore some reason I had an issue with this method. I fixed it by adding this condition.

### CODE REVIEW

**Comment by azamat-sharapov** [comment]
are you using vue-router on your app (where you got that error)?

**Comment by VincentGarreau** [comment]
I use vue-router, but it's not caused by transition hooks. It's when a v-for list is updated (from a computed source).

**Comment by yyx990803** [comment]
It's better to provide a repro of the scenario where you saw this error, because it's more likely a bug somewhere else that led to this. Fixing it here is not the ideal solution.

**Comment by VincentGarreau** [comment]
Right, i'll try to provide a repro. I close the the PR for now, thanks!

**Pull request closed without merging**
