### PR TITLE
fix(types): genChildren function with error normalizationType

### PR DESCRIPTION
**Pull request by skyline0705**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by skyline0705** [comment]
bug fix for https://github.com/vuejs/vue/issues/9181

first I try to change function `genChildren`, and change `normalizationType` to `ALWAYS_NORMALIZE`, it works in my case

but when I try this code:
```javascript
var vm = new Vue({
  el: '#demo',
  template: `
      <div>
        <foo v-for="item in list">
          {{ item }}
        </foo>
      </div>
  `,
  data: {
    list: undefined
  },
  components: {
    foo: {
      template: '<div><slot></slot></div>'
    },
  }
})

setTimeout(() => {
  vm.list = [1,2,3,4,5];
}, 1000);
```

I found it now works because the root element `div` has no attrs, and found the function `createElement` has an error params order;

so second I try to change file `src/compiler/codegen/index`
and change the function call `_c`, change the code
```javascript
code = `_c('${el.tag}'${
    data ? `,${data}` : '' // data
  }${
    children ? `,${children}` : '' // children
  })`
```
to
```javascript
code = `_c('${el.tag}'${
    data ? `,${data}` : ',undefined' // data
  }${
    children ? `,${children}` : '' // children
  })`
```
I think it will works, but…… the unit test shows that I'm wrong, there are many error 😭

finally I fix the `renderList` function, let it always return an array, and everything goes well……


I know use an `undefined` value in v-for is invalid, but before v2.5.16, it works well, I think it should be warn in the next version like v2.6.x, and should keep work in v2.5.x

**Comment by yyx990803** [comment]
I think it's better to handle it directly in `simpleNormalizeChildren` - it avoids allocating empty array on each render and allows the diff algorithm to take a faster path.

See 47487607fbb99339038cf84990ba341c25b5e20d

**Comment by yyx990803** [comment]
Ended up using your fix in 847e4937 when trying to apply additional optimization for the case... sorry!

**Comment by skyline0705** [comment]
Ok~ No problem~~And another thing, the fundamental cause of this is because the params order at function `createElement`, that is why I finally decided to change function `renderList`: the `createElement` calls are too flexible😂.

maybe there need a little more test case of compile template, like the test case `components with v-for and empty list, root element has no attrs` I added before. the steps is on the last comment https://github.com/vuejs/vue/pull/9182#issuecomment-446085762

**Pull request closed without merging**
