### PR TITLE
 fix: serialize-javascript vulnerability by updating package (#10910) 

### PR DESCRIPTION
**Pull request by staghouse**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Security Vulnerability

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by posva** [comment]
Note: there is a breaking change regarding how objects with an `undefined` value are serialized: https://github.com/yahoo/serialize-javascript/issues/57

**Comment by posva** [comment]
Closing in favor of https://github.com/vuejs/vue/pull/10904

**Comment by staghouse** [comment]
Please check again. My history got a bit hairy with the revert. If this PR is still broken I will close and open a clean PR without running the tests.

**Comment by staghouse** [comment]
Problem is I'll have to --no-verify passed the linter as it seems to correct some issues on commit, is this acceptable?

**Comment by posva** [comment]
it shouldn't be a problem but yes, you can do that and the PR might still be valid

**Comment by staghouse** [comment]
Closing in favor of https://github.com/vuejs/vue/pull/10914

**Pull request closed without merging**
