### PR TITLE
Select fix for IE & Edge

### PR DESCRIPTION
**Pull request by fergaldoyle**
RE: https://github.com/vuejs/vue/issues/3689

Fixes select (and multiple) for IE9, IE10, IE11 and Edge

`setTimeout` isn't ideal but `nextTick` doesn't work once an option has been selected and page refreshed.

### CODE REVIEW

**Comment by fergaldoyle** [comment]
For cases where a select element is inside a `v-if`, `hook:mounted` would have already been called. Using just `setTimeout` works fine.

**Comment by yyx990803** [comment]
Have you tried just changing the `bind` hook to `inserted` instead?

**Comment by fergaldoyle** [comment]
Changing [#L24](https://github.com/vuejs/vue/blob/054b96bd7079bf54a079d1f17bea3f215970fdea/src/platforms/web/runtime/directives/model.js#L24) to `inserted` only doesn't fix the issue. It seems you have for a certain period after insertion before re-setting selection.

When `inserted` is called,  `selectedIndex` is already `0` when it should be `-1`.

Further playing round with various scenarios (select elements in root template, sub components, inside v-if, inside v-for) the following two options work:

### 1
Add the `inserted` hook and place IE workaround here. Can't check for `selectedIndex === -1` as it's already been reset by IE. Using `setTimeout` causes minor UI flicker (where select element value is changing) so `setSelected` instantly called then called against in `setTimeout`.
```javascript
  inserted (el, binding, vnode) {
    if((isIE || isEdge) && vnode.tag === 'select') {
      // IE/Edge will set selectedIndex to 0 in cases
      // where it should be -1, force the select to refresh.
      setSelected(el, binding, vnode.context)
      setTimeout(() => {
        setSelected(el, binding, vnode.context)
      }, 0)
    }
  },
```

### 2
Similar to the current PR, workaround is placed in the `setSelected` function. `selectedIndex === -1` so workaround will only run when this is the case. To prevent recursion `_v_ieselectdone` state is saved on the el. `setSelected` is called twice, once in `nextTick` and once in `setTimeout` to prevent UI flicker
```javascript
  if ((isIE || isEdge) && el.selectedIndex === -1 && !el._v_ieselectdone) {
    // IE/Edge will set selectedIndex to 0 in cases
    // where it should be -1, force the select to refresh.
    el._v_ieselectdone = true
    nextTick(() => {
      setSelected(el, binding, vm)
    })
    setTimeout(() => {
      setSelected(el, binding, vm)
    }, 0)
  }
```

**Comment by yyx990803** [comment]
Hmm, using `inserted` seems to be working fine for me in all cases - can you specify where it's not working as intended?

**Comment by yyx990803** [comment]
Thanks a lot of looking into this - I need to get a release out before getting off work today so I implemented your 1st suggestion (with your credit in the commit message) - hope you don't mind!

**Comment by fergaldoyle** [comment]
I don't mind at all!

**Pull request closed without merging**
