### PR TITLE
fix(props): support BigInt in props type validation

### LINKED ISSUE #11126: Allow BigInt usage in templates
### What problem does this feature solve?
It would allow us to use numbers which is larger than MAX_SAFE_INTEGER. 

### What does the proposed API look like?
In HTML, `{{BigInt("100")}}`, `{{100n}}`, `{{2n * 50n}}` or `{{50n + 50n}}` should show "100" (it can be just simply string by using .toString()) at frontend.
At the moment using BigInt in "Mustache" syntax just throw error.
Sure, backup solution would be using external functions or converted into string and save it to variable. But using BigInt directly in HTML would be nice to have.
More Information about BigInt -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

### PR DESCRIPTION
**Pull request by AjiTae**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
Just a simple addition to make BigInt validation work.

Close #11126

### CODE REVIEW

**Comment by anhmv** [comment]
I don't think it has to support BigInt, BigInt rarely uses and not supported by most browsers.

**Comment by AjiTae** [comment]
> I don't think it has to support BigInt, BigInt rarely uses and not supported by most browsers.
Rarely, yes, but nonetheless. There is no way to do a BigInt type check now even if I want to. Like [Number, BigInt] - won't work.

**Comment by anhmv** [comment]
@AjiTae you might have to create the validator function for your props, for example:

```js
yourBigInt: {
  validator: v => typeof v === 'bigint',
}
```

**Review by mireinaa24hu — COMMENTED** [review]
okw

**Pull request merged**
