### PR TITLE
feat: add ssr template contentPlaceholder

### PR DESCRIPTION
**Pull request by lonelyclick**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
#5624

### CODE REVIEW

**Comment by dsonet** [comment]
I don't think should introduce this since it come with barely benefit.

**Comment by yyx990803** [comment]
Thanks for the PR, but I don't really think this is particularly useful. I'd rather have templates in all Vue SSR projects be consistent.

**Comment by JounQin** [comment]
Why not? What if we only need SSR for some specific urls, what means we need a temple for non-ssr requests. For now we must create two temples, or replace `<div id="app"></div>` to SSR default contentPlaceholder.

And also, there is an option of contentPlaceholder before 2.3.0, so it actually breaks some use cases which is not mentioned in SSR guide.

**Comment by yyx990803** [comment]
@JounQin not sure if I understand your use case - you mean you want to set the placeholder to something else so that the route does not SSR?

The previous option was in a separate package so technically it was not under Vue's version constraints.

**Comment by JounQin** [comment]
Yes, we shared same template for SSR and non-SSR requests before (our placeholder is `<div id="app"></app>` which is a valid root for non-SSR requests).

To developers, we're just migrating from one solution to another, and they share most of developing experience except `contentPlaceholder` option, so maybe it will be better if it's mentioned in document.

**Comment by yyx990803** [comment]
Ah, that's actually clever. Although I kinda feel it's not the use case this option should be designed for. You can easily use the same template file and do this when creating the renderer:

``` js
const renderer = createBundleRenderer({
   // ...
   template: template.replace('<div id="app"></div>', '<!--vue-ssr-outlet-->')
})
```

**Pull request closed without merging**
