### PR TITLE
caseInsensitive maybe more descriptive than expectsLowerCase

### PR DESCRIPTION
**Pull request by jingsam**

### CODE REVIEW

**Comment by fnlctrl** [comment]
Thanks, but `case-insensitive` is clear enough.
https://en.wikipedia.org/wiki/Case_sensitivity

**Comment by jingsam** [comment]
@fnlctrl As case-insensitive is more clear, why not use caseInsensitive instead?

**Comment by fnlctrl** [comment]
Oops.. Misread changes/original, sorry.
`expectsLowerCase` is also clear enough, and since it's just source code (not documentation), there's no practical to change it.

**Comment by jingsam** [comment]
Understand, but I am reading the source code now 😄

**Pull request closed without merging**
