### PR TITLE
Shortening the `You are running Vue.js in development mode...` consol…

### PR DESCRIPTION
**Pull request by ThomasLandauer**
…e message

Reason: The console is usually small, and this message consumed 3 lines.

I found this message at ~6 further places in the code. Should I change each? Or do you plan to have them generated from a centralized source?

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by smolinari** [comment]
There is a config variable, which you can set to turn it off.

https://vuejs.org/v2/api/#productionTip

Scott

**Comment by ThomasLandauer** [comment]
It's fine to have the message, I just think it should be shorter :-)

BTW: I can't get the global config change to work. Where would I have to put that `Vue.config.productionTip = false;`? Just above my first `var app = new Vue({ ...`?

**Comment by smolinari** [comment]
Should work right after the import of Vue in `main.js` or above your `app` assignment.

Scott

**Comment by posva** [comment]
This new message just tells you to visit a website while the other was explicit about the intention of the warning. I really prefer the old one

**Comment by ThomasLandauer** [comment]
@smolinari: I think something is wrong with this setting. When I load a page *for the first time*, I don't  get the tip in the console. But when I reload, I keep getting it. Does it work for you as expected?

@posva: I did keep the first sentence ("You are running Vue.js in development mode."), which tells you (more or less) everything that's really important. I deleted the second sentence ("Make sure to turn on production mode when deploying for production") which, well, is no new information after the first one...  
However, I don't really care about the exact wording. I'd just like to have it **in only one line** :-)

**Comment by luck2011** [comment]
@ThomasLandauer yours does make sense.

**Comment by smolinari** [comment]
> Does it work for you as expected?

It sure does. 

Scott

**Comment by yyx990803** [comment]
Thanks for the PR, but I also think the old one is more explicit.

**Pull request closed without merging**
