### PR TITLE
fix(keep-alive): solve memory leak probelm

### PR DESCRIPTION
**Pull request by JonathanChan94**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by posva** [comment]
Are you fixing a specific issue? https://github.com/vuejs/vue/issues?q=is%3Aissue+is%3Aopen+keep+alive Which one?
If not, can you provide a reproduction?

**Comment by JonathanChan94** [comment]
**Version**
2.6.11

**Reproduction link**
https://codesandbox.io/s/zealous-minsky-tv83s?file=/src/App.vue

**Steps to reproduce**
``` 
<template>
  <div id="app">
    <div class="nav">
      <router-link class="nav-item" to="/home">Home</router-link>
      <router-link class="nav-item" to="/about">About</router-link>
    </div>
    <keep-alive include="Home">
      <router-view/>
    </keep-alive>
  </div>
</template>
```
1.First in home route, click "Collect garbage" and "Take heap snapshot"(snapshot 1)
2.Click About link, then click Home link, then click "Collect garbage" and "Take heap snapshot"(snapshot 2)
3.Make comparison, search detached html

snapshot1
snapshot1
snapshot2
snapshot2
comparison
comparison

I use keep-alive to cache home page, when i click to about page then click back to home page, i found that the div of about page was still reachable, but that page should be destroyed.
Then i found that the cached home vnode was not latest, we can find div of about page from this vnode.
It will cause memory leak, so i modified to fix this.

**Comment by posva** [comment]
The detached number seems to be constant no matter how many times we navigate between home and about. There is no memory leak
Screenshot 2020-07-03 at 08 29 53

**Comment by JonathanChan94** [comment]
> Thank you for your PR but the detached number seems to be constant no matter how many times we navigate between home and about. There is no memory leak:
> 
> Screenshot 2020-07-03 at 08 29 53



> Thank you for your PR but the detached number seems to be constant no matter how many times we navigate between home and about. There is no memory leak:
> 
> Screenshot 2020-07-03 at 08 29 53

This is just a demo to describe the problem, about page only has one dom node, but if about page has so many dom nodes, it will cause memory leak. In my project, it actually happened.
I hope you can check it again. Thanks a lot.

**Comment by qtttttttttting** [comment]
@JonathanChan94 Excuse me, have you solved this problem ? I am confused now.

**Pull request closed without merging**
