### PR TITLE
ci(CircleCI Config): Migrate to CircleCI 2.0 with workflows

### PR DESCRIPTION
**Pull request by heug**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: CI Improvement

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
CircleCI 2.0 allows for faster performance and reduced overall time to build and test by utilizing parallel testing via workflows. The codebase and dependencies are downloaded, cached, and are then used as part of a common workspace for the different components in `npm run test`, which have been split into four parallel containers.

Tests should complete in around 1m45s once the initial testing and caching has been done with CircleCI 2.0, compared to around 4m currently.

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks for PR, but why is the v2 config file so much more complex? What's the advantage of this over the current shell script?

**Comment by heug** [comment]
Hi, thanks for reviewing!

Circle's v2 provides much more customization over v1, and as such requires a lengthier configuration file. The v2 config file in the PR pulls the code, restores and updates the dependency cache, and provides this environment as a common workspace in separate containers for the different types of testing that were present in `npm run test`. The different tests run in parallel now instead of sequentially, cutting the time to build and test by almost half compared to the v1 config.

**Comment by posva** [comment]
Isn't there a simpler syntax for that. 130 lines of yml config looks like an overkill 😭

**Comment by heug** [comment]
Unfortunately no, I did the best I could by using references at the top of the yml to avoid repeating many of the lines. I'd be happy to go back in and comment all the things so people can follow along and contribute more easily in the future if that sounds good!

**Comment by posva** [comment]
Personally, I think this can save quite some time. Having comments do help.
As a CircleCI user, v2 looked super interesting but when I wanted to use it, I was overwhelmed by how complicated it was compared to v1 (can work with zero config). It's clear how powerful it is in complex projects. Having you writing a config for vue makes it much easier understand how it works 🙂

**Comment by yyx990803** [comment]
I played with this in the CI branch and indeed it greatly speeds up the build, but the base Node image in CircleCI 2 doesn't have java so the Selenium-based e2e tests cannot be run. If anyone wants to take this over and find a suitable docker image to use, contributions are welcome.

**Comment by yyx990803** [comment]
@heug thanks again for the PR! We have enabled CircleCI 2 in https://github.com/vuejs/vue/pull/6627 :)

**Pull request closed without merging**
