### PR TITLE
fix(for): use IE compatible regex in v-for regex

### LINKED ISSUE #7946: Error when using v-for in IE10
### Version
2.5.16 / 2.5.17

### Reproduction link
[https://jsfiddle.net/plasmaeng/ndmjjkho/1/](https://jsfiddle.net/plasmaeng/ndmjjkho/1/)

### Steps to reproduce
Running the code below in IE10 will result in the following error:

```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Page Title</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="vue.js"></script>
</head>
<body>
<div id="app_test">
	<form>
	<select>
		<option v-for="value in L">{{value}}</option>
	</select>
	</form>
</div>

<script>
	var appTest = new Vue({
	el: '#app_test',
		data: {
			L : [ '1', '2' ,'3']
		}
	});
</script>
</body>
</html>
```

Here is the error message from IE10.
```
[Vue warn]: Error compiling template:

<div id="app_test">
	<form>
	<select>
		<option v-for="value in L">{{value}}</option>
	</select>
	</form>
</div>

invalid expression: Syntax error in  Raw expression: v-for="value in L"
invalid v-for alias "" in expression: v-for="value in L"
```

image

image

### What is expected?
`<option>` is generated from 1 to 3.

### What is actually happening?
`<option>` is not generated with error !!!

---
I have persuaded a senior for a long time to introduce Vue.js.
If this problem is solved, we plan to reorganize the site into Vue.js.
Please solve the problem.

### PR DESCRIPTION
**Pull request by posva**
Closes #7946

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by posva** [comment]
Credit to @schoonc for pointing out the fix

**Comment by cleptric** [comment]
Is there something left, I could help with, to get this merged?

**Comment by cyberzed** [comment]
@sodatea is there any plans for merging this one or it's left in the dark alone forever :)

**Comment by cleptric** [comment]
How can this take 6 months to get a fix for a breaking change, in a supported browser, getting merged? Does vue not care about IE10 anymore?

**Comment by TheWebTech** [comment]
I'm here to bump this PR again as @cleptric stated, this is a simple fix that fixes support for a major feature of Vue for IE.

**Pull request merged**
