### PR TITLE
perf: preinitialize typeCheck RegExp

### PR DESCRIPTION
**Pull request by SebastianSpeitel**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Performance improvement

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

After looking at the performance of one of my apps, I noticed, the function, that took the most time summed up was `getType()` , defined in [1] taking 200ms. I noticed the regular expression getting created for each call and measured again including the proposed improvement, which took the time down to 150ms. To make sure I changed it back to confirm and it again timed at 200ms.

[1]
https://github.com/vuejs/vue/blob/b07087deae060244fe5d9651b38dc5f1e79667a9/src/core/util/props.js#L182-L185

### CODE REVIEW

**Comment by SebastianSpeitel** [comment]
Maybe further improvements could be made by removing the regular expression completely and using standard string manipulation methods.

**Comment by SebastianSpeitel** [comment]
Is there anything else, that needs to be done before merging? @posva

**Comment by posva** [comment]
@SebastianSpeitel You don't need to do anything else, thank you :)

**Comment by SebastianSpeitel** [comment]
I made this PR 2 months ago. Is there a reasons for this taking so long?

**Comment by lefreet** [comment]
@SebastianSpeitel   cached it may be better ?

```js
  const getType = cached(function getType (fn) {
    var match = fn && fn.toString().match(/^\s*function (\w+)/);
    return match ? match[1] : ''
  })
```

**Comment by SebastianSpeitel** [comment]
> @SebastianSpeitel   cached it may be better ?
> 
> ```js
>   const getType = cached(function getType (fn) {
>     var match = fn && fn.toString().match(/^\s*function (\w+)/);
>     return match ? match[1] : ''
>   })
> ```

Both could be optimal.
Compile the regex only once *and* compute the type of each object only once.

**Comment by lefreet** [comment]
but the `fn.toString` is a expense also, for every function  @SebastianSpeitel   sorry my later comment

**Pull request merged**
