### PR TITLE
chore: upgrade serialize-javascript

### PR DESCRIPTION
**Pull request by posva**
**What kind of change does this PR introduce?** (check at least one)

Security update from https://github.com/vuejs/vue/issues/11427 and https://app.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-570062

Breaking changes listed at https://github.com/yahoo/serialize-javascript/releases

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Security bump

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by sugiyama-akina** [comment]
Hi. When will this pull request be merged?
I'm using vue-server-renderer, but I'm having trouble fixing the serialize-javascript vulnerability.

**Comment by SirMishaa** [comment]
I have the same security problem as @sugiyama-akina , a merge is planned soon please ?

**Comment by dargmuesli** [comment]
@yyx990803 will there be a new 2.6 release containing this security fix?

**Comment by yyx990803** [comment]
2.6.12 has been released.

**Comment by dargmuesli** [comment]
Great! Thank you very much! ❤

**Pull request merged**
