### PR TITLE
add modifier key modifiers for v-on

### PR DESCRIPTION
**Pull request by KingMario**
add ctrl, shift and alt modifiers for v-on

### CODE REVIEW

**Comment by davemerrill** [comment]
I know I'm jumping in way late, but what's happening with this? There are tons of seemingly unrelated comments, it's marked closed but GH can't show the diff, and I don't see anything referring to modifiers in current 201 source. Is GH lost in space? What needs to happen if that's the case?

**Comment by KingMario** [comment]
@davemerrill since this pr is closed but not merged, and the repo branch structure had changed a lot during the release of Vue 2.0, I (by mis-understanding of the mechanism of pr) re-forked the repo. That's why you can't see the diff.
I don't know why this feature is not accepted, and you may put a feature request in the issues for everybody to discuss. I have the backup of that part, and can push it to a branch in the repo I forked anytime.

**Comment by yyx990803** [comment]
@KingMario this seems to be closed automatically by GitHub when I switched the branches. I think this could be a valid feature, feel free to re-submit.

**Comment by KingMario** [comment]
@yyx990803 just submitted this feature for both v1.0 and v2.0

**Comment by davemerrill** [comment]
Thank you both for moving this forward. So this should appear in 2.0.2? Any idea when that might be released?

**Pull request closed without merging**
