### PR TITLE
added support for parsing of space delimitted paths

### PR DESCRIPTION
**Pull request by lopugit**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks for your contribution.

However, as its name indicates, `parsePath` only handle path name delimited by dot, like `obj.pathName.noSpace`. Bracket indexing expression `ob['some pathh']` isn't supported. So we cannot accept space in path.

**Comment by lopugit** [comment]
@HerringtonDarkholme how is it not supported though? How do you access the dot delimited properties? Isn't bracket index expression the only way? I've been using it for a few hours and it's working fine for me, I can imagine there might be some breaking bugs but I thought that since you're parsing a string into paths all you do is split on a dot, I wrote a library that uses the same principle, I can't see any reason to be splitting on anything but a dot and doing anything else with the property strings, split or not split, do they get processed at all besides splitting on dot?

**Comment by HerringtonDarkholme** [comment]
`grep -R parsePath src -A 9`

```
src/core/util/lang.js:export function parsePath (path: string): any {
src/core/util/lang.js-  if (bailRE.test(path)) {
src/core/util/lang.js-    return
src/core/util/lang.js-  }
src/core/util/lang.js-  const segments = path.split('.')
src/core/util/lang.js-  return function (obj) {
src/core/util/lang.js-    for (let i = 0; i < segments.length; i++) {
src/core/util/lang.js-      if (!obj) return
src/core/util/lang.js-      obj = obj[segments[i]]
src/core/util/lang.js-    }
--
src/core/observer/watcher.js:      this.getter = parsePath(expOrFn)
src/core/observer/watcher.js-      if (!this.getter) {
src/core/observer/watcher.js-        this.getter = function () {}
src/core/observer/watcher.js-        process.env.NODE_ENV !== 'production' && warn(
src/core/observer/watcher.js-          `Failed watching path: "${expOrFn}" ` +
src/core/observer/watcher.js-          'Watcher only accepts simple dot-delimited paths. ' +
src/core/observer/watcher.js-          'For full control, use a function instead.',
src/core/observer/watcher.js-          vm
src/core/observer/watcher.js-        )
src/core/observer/watcher.js-      }
```

**Comment by lopugit** [comment]
@HerringtonDarkholme 

`obj = obj[segments[i]]` So it's using bracket notation?

**Comment by HerringtonDarkholme** [comment]
> The expression only accepts simple dot-delimited paths. For more complex expression, use a function instead.

Let me clarify what does this mean. `parsePath` is only used in `$watch` and `$watch`'s string argument only accepts simple dot-delimited path as convienence.

Dot-delimited path is a simple and valid expression in JavaScript, while `obj.some path` isn't.
Whether it works coincidentally with current implementation or not doesn't matter whether it is appropriate to be accepted as a public API.

Consider, if space can be accepted as object path, why minus, divide cannot? I can conceive a lot of CSS-in-JS users will use `background-color` as key name. Accepting non identifier symbol just breaks the simple concept of dot-delimiteed path.

Please do use function as watcher expression. Or, you can use your own wrapper function in your application.

```ts
function p(path) {
   const segments = path.split('.')
   return function () {
     const obj = this
     for (let i = 0; i < segments.length; i++) {
       if (!obj) return
       obj = obj[segments[i]]
     }
     return obj
   }
}

this.$watch(p('my space.my api.my data'), handler)
// only three more characters, two more key strokes if a decent editor is used
```

**Comment by lopugit** [comment]
@HerringtonDarkholme ohh you can actually pass the object straight through, that works well, I'm using a get function like that already to build objects out of strings, hence why I was surprised the watch function didn't allow spaces.

In my opinion having spaces is pretty awesome for readability and in general. 

I don't believe it's a non-identifier symbol is it? I just read up on the variable name javascript docs a little

**Comment by yyx990803** [comment]
`$watch`'s expression parse is intentionally limited - it's meant as a convenience API only, so anything more complex than dot-delimited paths should use a function getter instead.

**Comment by lopugit** [comment]
@yyx990803 @HerringtonDarkholme just coming back to this, shouldn't watching include any valid javascript property path? expression parse just has to separate on dots, that's literally all, and it would support minuses, plusses, spaces, etc... ? if I can do ```data(){ return { "some property" : true } }``` I should be able to do ```{ watch: { "some property" } }```

come on?

**Comment by Justineo** [comment]
> if I can do `data(){ return { "some property" : true } }` I should be able to do `{ watch: { "some property" } }`

What if you have this:

```js
{
  data () {
    return {
      'some.property': true,
      some: {
        property: false
      }
    }
  },
  watch: {
    'some.property' (val) {
      // ?
    }
  }
}
```

**Comment by lopugit** [comment]
> > if I can do `data(){ return { "some property" : true } }` I should be able to do `{ watch: { "some property" } }`
> 
> What if you have this:
> 
> ```js
> {
>   data () {
>     return {
>       'some.property': true,
>       some: {
>         property: false
>       }
>     }
>   },
>   watch: {
>     'some.property' (val) {
>       // ?
>     }
>   }
> }
> ```

yeah that's a good point but who in their right mind uses dots in their property names :')

**Comment by Alinawaz-786** [comment]
do you have any idea to use the love streaming api in laravel php

**Comment by lopugit** [comment]
@Alinawaz-786 what?

**Comment by Alinawaz-786** [comment]
Live streaming Videos

Anyone have any idea to live streaming videos api

any how to use this API

**Comment by lopugit** [comment]
@Alinawaz-786 this is not the place to ask about that? I don't know sorry.

**Pull request closed without merging**
