### PR TITLE
fix: computed not cache watchers define

### PR DESCRIPTION
**Pull request by guhongjie**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by guhongjie** [comment]
The default value of compute object cache is not considered

**Comment by posva** [comment]
Do you have a boiled down repro or a test case that was failing before the fix that we can look at?

**Comment by Justineo** [comment]
Thanks for your contribution. But `cache: false` for a computed property is already deprecated in v2: https://vuejs.org/v2/guide/migration.html#cache-false-deprecated

Instead of this PR, I think the occurence here should also be removed:

https://github.com/vuejs/vue/blob/06d4ad40a49e85e678ce2aa8fac0ecf2176f86e2/src/core/instance/state.js#L223

**Comment by Justineo** [comment]
So I'm closing this. Feel free to propose another PR to remove the unused `userDef.cache`. Thanks for your interests!

**Pull request closed without merging**
