### PR TITLE
fixing setTextContent for IE 10

### PR DESCRIPTION
**Pull request by mini-eggs**
<!--
Please make sure to read the Pull Request Guidelines:
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [X] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [X] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

IE 10 was throwing errors when this function was called. `Invalid arguments`. This PR fixes the error I've been experiencing.

### CODE REVIEW

**Comment by mini-eggs** [comment]
For some reason my description did not make it over. I'll update back in a second.

**Comment by nickmessing** [comment]
Hey, please undo the `dist/` folder changes and space before funciton parentheses.

**Comment by mini-eggs** [comment]
@nickmessing Will do.

Also, after more testing this didn't totally fix my issue. Thinking of making this fallback to innerText on IE11. Any qualms about this?

**Comment by nickmessing** [comment]
@mini-eggs, I don't know why you have issues since `node.textContent=` setter is available in IE9+. I didn't use windows for the last 4 years so I'm not sure I can help you with that, I suggest you check the browser market share and make sure you need IE9-10 support, if you do then try to debug exactly why `node.textContent=` doesn't work.

**Comment by posva** [comment]
Do you have a minimal repro of the original issue?

**Comment by mini-eggs** [comment]
I do not, it's a large private codebase. After a better look into the issue this morning I'm convinced this is not an issue with Vue.

We use the lib countUp.js within our Vue templates. Both Vue and countUp were changing the node where this occurred at the same type. Creating a computed variable in the Vue instance fixed the issue.

**Comment by posva** [comment]
Ok! No worries. Thanks for the pr though ☺️
It's pretty cool you decided to directly do the pr but it's better if you
provide a repro at the same time since no issue exist. You can even do it
in two steps if you prefer: create the issue and immediately after the pr
💯

**Pull request closed without merging**
