### PR TITLE
fix (#8731): drop enumerated attrs

### LINKED ISSUE #8731: Drop special logic for “enumeratedAttrs”
### Version
2.5.17

### Reproduction link
[http://jsfiddle.net/Justineo/upwrqm0z/](http://jsfiddle.net/Justineo/upwrqm0z/)

### Steps to reproduce
Bind `'plaintext-only'` or an unsupported value to `contenteditable` attribute.

### What is expected?
Rendering `contenteditable="plaintext-only"` for the element.

### What is actually happening?
`contenteditable="true"` is rendered.

---
For reference:

| `:contenteditable` | `contentEditable` in Vue | `contentEditable` in HTML ||
| -- | -- | -- | -- |
| `""` | `'true'` | `'true'` ||
| `"false"` | `'false'` | `'false'` ||
| `"true"` | `'true'` | `'true'` ||
| `"plaintext-only"` | `'true'` | `'plaintext-only'` | ❗️ |
| `"foo"` | `'true'` | `'inherit'` | ❗️ |
| `null` | `'false'` |||
| `undefined` | `'inherit'` |||
| `false` | `'false'` |||
| `true` | `'true'` |||

Vue currently treat `enumeratedAttrs` as enumerated attributes with only `'true'`/`'false'` values (boolean-like enumerated attributes) and this made them behave like boolean attribtues. While actually these attributes may have more than two states and are extensible for other values. For example, in HTML, `contenteditable`'s corresponding IDL attribute `contentEditable` resolves to `'inherit'` instead of `'false'` when `contenteditable` is not  present. And the latest W3C draft has also defined more possible values for it (`'plaintext-only'` is already accepted in Chrome) so we have to remove this logic, otherwise developers can't leverage these new features.

And if we drop the `enumeratedAttrs` thing and treat them like other ordinary attributes, there will be some influence on the following cases:

| `v-bind` | before | after |
| -- | -- | -- |
| `null` | `'false'` | / |
| `false` | `'false'` | / |

I'm not sure if we should regard this as breaking because we never documented this usage that binding `null`/`false` to `contenteditable`/`draggable`/`spellckeck` will be resolved as `'false'`.

### PR DESCRIPTION
**Pull request by Justineo**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No
- [x] Not sure

If yes, please describe the impact and migration path for existing applications:

As explained in #8731.

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by yyx990803** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

The logic is still needed to coerce `true` and `false` to `"true"` and `"false"` - we just need to allow additional values.

**Comment by Justineo** [comment]
Then maybe we should coerce all boolean bindings for non-boolean attributes to string. There are other attributes like `aria-hidden` which accept `'true'`/`'false'` values. Now it seems that we are coercing `true` but not `false`. Is it better to apply this coercing to all normal attributes? There seems no need to have special logic for enumerated attributes. @yyx990803

**Comment by yyx990803** [comment]
Hmm that's true... however, dropping the logic altogether would technically be a breaking change, as code that previous produced valid usage would now require manual coercing from the user.

So I think for 2.x it's better to just loosen the coercing to skip non-boolean values so that other values for `contenteditable` can be used.

**Comment by yyx990803** [comment]
I think for v2 we need to keep as much backwards compat as possible... in e632e9a0 I've added special treatment for `contenteditable` for now. Most aria-x attributes have explicit treatment of non-listed values mandated in the spec so it's less of a problem... In v3 we will not do any coercing.

**Pull request closed without merging**
