### PR TITLE
Refactor: get rid of toArray method

### PR DESCRIPTION
**Pull request by lusarz**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by nickmessing** [comment]
Since at the moment we transpile vue to ES5.1 for IE support - that does not bring any benefit and actually decreases performance:
```js
  for (var _len = arguments.length, b = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
    b[_key - 1] = arguments[_key];
  }
```

**Comment by lusarz** [comment]
I think main benefit of these changes is related with code quality. If it is possible to write something with less amount of code, why don't do it ?

I see also a few places in `vue` code where spread operator like `...args` is used, so it would be nice to be consistent:
https://github.com/vuejs/vue/blob/f2b476d4f4f685d84b4957e6c805740597945cde/src/core/observer/array.js#L27

https://github.com/vuejs/vue/blob/472a2896bd4f156be168edfecb6ac432b853beb4/src/platforms/weex/entry-framework.js#L163

**Comment by nickmessing** [comment]
You are right there, it should be consistent, but I am not so sure about code quality. Sometimes I'd rather think more about performance when developing a framework. And using `Array.prototype.slice.call(list, start)` may bring performance benefit depending on array usage (more info [here](https://v8project.blogspot.ro/2017/09/elements-kinds-in-v8.html)). Probably needs more feedback from the team.

**Comment by yyx990803** [comment]
The original usage of `toArray` instead of spread arguments throughout codebase is intentional. Using `...args` results in duplicated inline code chunks being generated, causing larger bundle sizes, slower parsing and less optimized performance.

**Pull request closed without merging**
