### PR TITLE
fix(types): add new directive types to options in favour of deprecated

### PR DESCRIPTION
**Pull request by iamandrewluca**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

image

### CODE REVIEW

**Comment by iamandrewluca** [comment]
Related https://github.com/vuejs/vue/pull/12792

**Comment by iamandrewluca** [comment]
Will Vue2 receive any other updates? 👀

**Comment by doommm** [comment]
Any progress ? encountered same problem in vue 2.7, and it causes entire component type checking to fail.
image
image

**Comment by Explosion-Scratch** [comment]
copilot:summary

**Pull request closed without merging**
