### PR TITLE
keep consistency in dev and prod env

### PR DESCRIPTION
**Pull request by jingsam**

### CODE REVIEW

**Comment by yyx990803** [comment]
Does this cause any problem in production?

**Comment by jingsam** [comment]
Noop, I just thought that vue should have the same behaviour in development and production enviroment except extra warnings.

**Comment by jingsam** [comment]
One more thing, I think this [line of code](https://github.com/jingsam/vue/blob/dev/src/core/global-api/extend.js#L32) should be deleted in Vue 2. In vue 1, `name` will be used as a function name, such as:
name='MyComponent' => function MyComponent () {this._init(options)}
However, in Vue 2, no matter what name is, always use  `function VueComponent() {this._init(options)}`

**Comment by yyx990803** [comment]
@jingsam true, I think this PR can be changed to simply removing that line.

**Comment by jingsam** [comment]
Ops, CI failed in this [test](https://github.com/vuejs/vue/blob/dev/test/unit/features/options/name.spec.js#L23-L28):`
```
  it('when incorrect name given it should not contain itself in self components', () => {
    const vm = Vue.extend({
      name: 'Hyper*Vue'
    })

    expect(vm.options.components['Hyper*Vue']).toBeUndefined()
```

In fact, in Vue 2, there are no limitations on the name of components. Even invalid name can be registered. The only limitation is whether the virtual dom  can parse the name tag into  the corresponding component. For example, `Hyper*Vue` can be registered but `<Hyper*Vue></Hyper*Vue>` can not be parsed by virtual dom correctly. `_HyperVue` is an invalid name but it works, as `<_HyperVue></_HyperVue>` can be parsed.

@yyx990803 so, shall I delete that unit test case ?

**Comment by yyx990803** [comment]
Yeah, I think that test case can be removed.

**Pull request merged**
