### PR TITLE
ReadMe Updated

### PR DESCRIPTION
**Pull request by Shivansh2407**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Description:**
This PR aims to remove a non working link and also transform the Gold from readme file to the table.

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@yyx990803 Please Review this and Let me know. I am glad to contribute to Vue Repo. This is my first PR, Happy to Contribute

**Comment by yyx990803** [comment]
Sorry but the sponsor sections in the README file is auto generated.

**Comment by xerosanyam** [comment]
btw, congrats on your first PR @Shivansh2407 !  🙂

**Comment by Shivansh2407** [comment]
Thank you @xerosanyam and @yyx990803👍

**Pull request closed without merging**
