### PR TITLE
feat: Add `async` to body scripts (update: Use `defer` instead)

### PR DESCRIPTION
**Pull request by Atinux**
**What kind of change does this PR introduce?** (check at least one)

- [x] Feature

**Does this PR introduce a breaking change?** (check one)

- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] New/updated tests are included
- [x] All tests are passing: https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#development-setup

If adding a **new feature**, the PR's description includes:

`async` tag let the scripts to not block the render of the page, and since it's for SSR, the scripts don't have to be loaded before the first render.

### CODE REVIEW

**Comment by blake-newman** [comment]
Looks good although I can't find any specification on the behaviour of multiple async script tags. Does it keep the linear order or will it execute as soon as script is parsed. 

If the latter then there could be race conditions. This may be worth an investigation.

**Comment by Atinux** [comment]
Based on this answer: http://stackoverflow.com/questions/8996852/load-and-execute-order-of-scripts

It may be better to use `defer` instead of `async` to keep the order, what do you think?

**Comment by blake-newman** [comment]
Good find :) 

Yeah defer is the best, as it will keep predicability.

**Comment by Atinux** [comment]
Commits updated 👍

**Pull request merged**
