### PR TITLE
Replace var with proper let/const

### PR DESCRIPTION
**Pull request by phanan**
I guess 2.0 is a perfect opportunity to adapt ES6 fully. Using `const` and `let` instead of `var` is a good start.

### CODE REVIEW

**Comment by azamat-sharapov** [comment]
Interesting.. what does Evan use to automatically add github labels to PRs? :)

**Comment by phanan** [comment]
@azamat-sharapov I'm not sure, but a quick search for "Github auto labels" yields several results for me ;)

**Comment by egoist** [comment]
Whatever, he must be using the github webhook 😂

**Comment by azamat-sharapov** [comment]
@phanan well those results don't give anything obvious, so I thought maybe it's custom script running on some server.. sorry for offtop though :)

**Comment by phanan** [comment]
@azamat-sharapov True that… Let's hope @yyx990803 unveils his secret.

**Comment by nervgh** [comment]
@phanan 
> I guess 2.0 is a perfect opportunity to adapt ES6 fully. Using const and let instead of var is a good start.

The constants should be in UPPERCASE (a best practice / naming conventions)
Example https://github.com/nervgh/recursive-iterator/blob/master/src/RecursiveIterator.js#L8

**Comment by azamat-sharapov** [comment]
@nervgh can't agree with that, it isn't really constant.. `const` in JS is different, you probably already know how const works, compared to many other languages.

**Comment by phanan** [comment]
What @azamat-sharapov said.

**Pull request merged**
